### ISSUE TITLE
Add Client SSL Profile and Server SSL Profile to New/Set-VirtualServer

### ISSUE THREAD

**Issue by VivoSomnio** [joel74/POSH-LTM-Rest#105]
I would like to be able to add Client and Server SSL Profiles to new and existing Virtuals.  For either I imagine it being simply another parameter, for example:
-ClientSSLProfile "/Common/clientssl"
-ServerSSLProfile "/Common/serverssl-insecure-compatible"

**Comment by joel74** [comment]
This option already exists. Both New-VirtualServer and Set-VirtualServer accept an array of profile names. Since profiles with the same name can't exist as both client and server profiles, the F5 knows where to apply the profiles.

So, for example, this call successfully added the clientssl and serverssl profiles:

`new-virtualserver -F5Session $f5session -Name test3z -DestinationIP 192.168.16.98 -ipProtocol tcp -DestinationPort 80 -ProfileNames 'clientssl','serverssl'`

**Comment by VivoSomnio** [comment]
I must be missing something.  I'm trying to set the following profiles: HTTP Profile, Client SSL Profile, Server SSL Profile, Default Persistence Profile, Fallback Persistence Profile

New-VirtualServer -ProfileNames 'httpProfile','clientSSLProfile','serverSSLProfile','defaultPersistenceProfile','fallbackPersistenceProfile'

This fails with the following:
Invoke-F5RestMethod : "400 Bad Request: 01070161:3: A persistence profile must be set via the virtual server persist    
attribute.                                                                                                              
At C:\Users\Public\Documents\InstallChannels\F5-LTM\1.4.135\Public\New-VirtualServer.ps1:155 char:7                     
+       Invoke-F5RestMethod -Method POST -Uri "$URI" `                                                                  
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                  
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                                      
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-F5RestMethod

**Comment by joel74** [comment]
No, you're not missing something, just expanding the scope of your request. :)
Apparently persistence profiles are handled separately from other profiles (i.e. client and server).
iControlREST can accept an array of persistence profiles, as well as a value for the fallback persistence profile. 

I'll work on adding these two params, but I also want to understand how setting persistent profile defaults works. Per F5's docs:
"If [/persist/default] is set to "yes", this indicates that this profile will be the default when no iRule overrides it. If no persistence profile default is yes and persistence is not set by iRule, then no persistence profile will be used. Defaults to yes if only one profile is provided, or no if multiple persistence profiles are provided."

In the UI, I see two dropdowns - one for Default Persistence Profile and one for Fallback Persistence Profile. There's no indication that multiple persistence profiles can be assigned to a virtual server. Have you seen that that's possible?

Cheers,
Joel

**Comment by VivoSomnio** [comment]
Hi Joel,

 

Sorry, I wasn’t clearer in my initial request as I assumed the issue was elsewhere.

 

With regards to the persistence profiles, you can actually set multiple programmatically (and it will show as multiple in the dropdown), however in my case I actually just want to set the default and fallback.

 

Warm regards,

Scott

**Comment by joel74** [comment]
Ok, thanks, Scott - that's good to know. I'll continue working on updating the module to accommodate setting persistence profiles, both for your scenario and for people who want to assign multiple ones to a virt. server. 

Cheers,
Joel

**Comment by joel74** [comment]
This will be resolved with the changes made in #112

**Comment by joel74** [comment]
#112 has been merged.
