### ISSUE TITLE
Unable to define Route Domain when Adding Pool Member

### ISSUE THREAD

**Issue by drryu** [joel74/POSH-LTM-Rest#108]
Add-Pool member takes an ipaddress as an IPAddress object. 

Adding a route domain to the ipaddress does not work. e.g. 192.168.180.25%200, and throws a validation exception.

**Comment by drryu** [comment]
I submitted a pull request to fix this issue. Please review

**Comment by joel74** [comment]
Thanks for the catch and the pull request. I'll review the changes locally. After an initial visual pass, the only thing I'm wondering about is the change from calling Get-PoolMember with an Address object to calling is with an IP address string. Other than that, it seems pretty straightforward.
Cheers,
Joel

**Comment by drryu** [comment]
Thanks for the quick response.

Get-PoolMember already takes an IPAddress string array. Adding the %<route_domain> seems to work without any code modification.

**Comment by joel74** [comment]
Cool. It looked like we were passing an object to Get-PoolMember - guess it was just transforming the address to a string as needed. Code works as expected. One small comment - it's considered a best practice to not change the order of parameters in public methods and functions, so my recommendation is to reorder the params with $RouteDomain at the end of the list. Personally I think people shouldn't rely on param order and not specifying the param names should be a bad practice, but for the time-being I'm deferring to the general recommendation. Once that's tweaked, I'll approve the pull. Cheers.

**Comment by drryu** [comment]
Thanks for the tip. :). I have changed the order and made my commit to the branch.

Thanks,
Rashief

**Comment by joel74** [comment]
Resolved with pull request #109 . Cheers, Rashief.
