### ISSUE TITLE
Upload Module to PowerShell Gallery

### ISSUE THREAD

**Issue by ScriptAutomate** [joel74/POSH-LTM-Rest#12]
Can this be published to the PowerShell Gallery, and updated in PowerShell Gallery whenever the Master branch is updated?

**Comment by joel74** [comment]
I'd be happy to, if I can figure out how to reference the TunableSSLValidator module.
This is what I currently get when I attempt to publish:

Publish-PSGetExtModule : PowerShellGet cannot resolve the module dependency 'TunableSSLValidator' of the module 'f5-ltm' on the repository 'PSGallery'. Verify that the dependent module 
'TunableSSLValidator' is available in the repository 'PSGallery'. If this dependent module 'TunableSSLValidator' is managed externally, add it to the ExternalModuleDependencies entry in the 
PSData section of the module manifest.

Examples of how to do this seem to be lacking online. Any ideas?

**Comment by joel74** [comment]
I've removed the dependency of this module on the TunableSSLValidator module, and am using a C# class instead now, so I was able to publish to the PowerShell Gallery.
https://www.powershellgallery.com/packages/f5-ltm/
