### ISSUE TITLE
RouteDomain and Address param [in]consistency

### ISSUE THREAD

**Issue by vercellone** [joel74/POSH-LTM-Rest#127]
### Route Domain
#108 reveals that F5 IP Address fields can optionally include a [Route Domain](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-ip-routing-administration-11-2-0/2.html) suffix (i.e. %1, %4), which is currently not supported by System.Net.IPAddress.

### Address Parameter [In]Consistency
Currently, some functions (Get-PoolMember) declare Address as string[] and others (Add-PoolMember) as IPAddress[] (and Add-PoolMember now has a separate RouteDomain parameter). Instead, we should utilize a single param of a custom type which is composed of an IPAddress and a RouteDomain.

### ComputerName [In]Consistency
Some Functions have an explicit ComputerName param, others apply a ComputerName alias to Address, still others apply a ComputerName alias to Name.

**Comment by joel74** [comment]
Re: ComputerName inconsistencies, I'm definitely in favor of changing the instances of where ComputerName is an alias for [IP] address. It looks like it will require a bit of rethinking of the login in the *-PoolMember functions.

Re: the question of System.Net.IPAddress vs. a custom F5 IP Address including route domain, I'm undecided, though maybe as long as it's somewhere in the ReadMe and there's a good example showing how to include the route domain in the custom F5 Address, that's the best solution, though just using 2 params - Address and RouteDomain - seems simpler.

**Comment by elijahgagne** [comment]
**Address parameter**: I like what you did with [PoshLTM.F5Address]. I think this gives us a lot of flexibility to create an address from a hostname or ip address with the optional route domain.

I can't think of why you'd do this, but would you want to have a name, IP, and route domain? You can accomplish that with your struct by doing something like:

```
PS C:\Users\egagn> $a = [PoshLTM.F5Address]"server"
PS C:\Users\egagn> $a.RouteDomain = "4"
PS C:\Users\egagn> $a

ComputerName IPAddress   RouteDomain
------------ ---------   -----------
server        10.0.0.0             4
```

That's not a scenario I would use. But if you think it's worth it, you could add another constructor that takes two parameters to allow creating that F5Address without needing to add the RouteDomain as a second step.

Fixing up ComputerName just makes sense.

**Comment by vercellone** [comment]
@joel74 There is no need to construct an F5Address object.  As @elijahgagne demonstrated above, you certainly can, but it is not necessary.  F5Address allows you to specify a string, IPAddress, or F5Address value.

Prior to F5Address the following use-cases were supported:

```PowerShell
-Address 10.0.0.1
-Address '10.0.0.1'
-Address ([System.Net.IPAddress]'10.0.0.1')
```
F5Address supports those use-cases, as well as expanding the possibilities to include:
```PowerShell
-Address '10.0.0.1%4'
-Address MyComputerName
-Address ([PoshLTM.F5Address]'10.0.0.1')
```
 It is fully backwards compatible in that regard, whether the previous param type was IPAddress or string.

**Comment by vercellone** [comment]
Re: ComputerName

I personally don't use -ComputerName.  At all.  As usual, my goal was to simplify while avoiding/minimizing breaking changes.  If I've introduced a breaking change, let me know and I'll review my choices.

Otherwise, I am content with the aliases as reflected in this PR.  But, I'll defer to you guys as to whether the cost of breaking changes is justified.

@joel74 I don't know what you mean by "a bit of rethinking of the login in the *-PoolMember functions".

**Comment by vercellone** [comment]
@elijahgagne I couldn't think of a scenario where one would know the route domain and not the IPAddress, so I felt that my implementation served to deliberately discourage that use case without necessarily preventing it (as you've demonstrated).  But, if anyone feels there is value in it, I am not opposed to it.

**Comment by joel74** [comment]
From what I can tell, no functions explicitly take ComputerName as a param. The Test-Functionality function does use the ComputerName aliases, but I'd be happy to revamp that function to use Address instead of ComputerName.

My vote would be to not have ComputerName as an alias for Address. It doesn't make sense - they're two different types of values. The UI doesn't accept a computer name in the address field. We've just been thoughtful and done behind-the-scenes conversion of computer name to IP address, which probably wasn't smart. But if we're considering changing params and aliases, we should also consider expanding the *-PoolMember functions to accept FQDN nodes, since that has been requested (Issue #117 )  (Jason, I meant to type "logic in the *PoolMember functions," not "login.")

I'm in favor of F5Address accepting:
-Address '10.0.0.1%4'
-Address ([PoshLTM.F5Address]'10.0.0.1')

**Comment by vercellone** [comment]
I agree that ComputerName should not be an alias for Address.  I like the convenience that supporting a computername value for -Address provides, but we can still do that without the alias.

Just be aware that: [Add-PoolMember](https://github.com/joel74/POSH-LTM-Rest/blob/master/F5-LTM/Public/Add-PoolMember.ps1) does currently have an explicit -ComputerName param.  And, most (if not all) \*-\*Pool\*Member* functions have a ComputerName alias applied to $Address.  Confirm you are OK with breaking all of those and I will make it so.

**Comment by elijahgagne** [comment]
I can't make the case for adding another constructor to [PoshLTM.F5Address], it's not something I would use. 

Completely removing ComputerName would not affect me.

**Comment by joel74** [comment]
I think my preference would be to remove the default param values in Add-PoolMember for $Name and $Description so they're not using $Address.ComputerName, before merging this into the master branch. Also, it seems like this is the time to discuss if we want 'ComputerName' as part of the new F5Address struct. I feel like it's not really a part of this, so I'd rather pull it out before committing, instead of trying to excise it later. Thoughts?

**Comment by vercellone** [comment]
OK.  Breaking changes forthcoming.  Don't say I didn't warn you. :)

Do you want to keep existing ComputerName aliases applied to $Name?  I'll assume you do, until I hear different.

**Comment by joel74** [comment]
Yes, we can separate this from the work that would be involved in cleaning up the ComputerName aliases applied to Name. Thanks. So you're okay with not having ComputerName in the F5Address struct?

**Comment by vercellone** [comment]
Absolutely.  I only included it to avoid breaking the existing Add-PoolMember default: $Description=$ComputerName.

F5Address can still support name resolution, it just won't store the requested string.

**Comment by vercellone** [comment]
Done: 26de845 #128

**Comment by joel74** [comment]
Looks good to me. All my tests with the *-PoolMember and *-Node functions passed. So we're good? @elijahgagne, you're happy?

**Comment by elijahgagne** [comment]
I am happy. I may try to build out a fuller test suite later, but everything I've thought of to test looks good.
