### ISSUE TITLE
Get/Test-Node mismatch

### ISSUE THREAD

**Issue by vercellone** [joel74/POSH-LTM-Rest#129]
All is well when -Partition is specified explicitly or derived from a fully qualified -Name.  When it isn't, Get/Test-Node outputs don't match.
```PowerShell
# Assuming w.x.y.z is a valid address of an existing F5 node
Test-Node -Address w.x.y.z # Returns True, even if the node is not in the Common partition
Get-Node -Address w.x.y.z # Returns $null if the node is not in the Common partition
```
Test-Node should probably default to searching the Common partition to conform with other Functions.  Thoughts?

**Comment by joel74** [comment]
I think that makes sense. If no partition is specified for Test-Node, search Common by default.

**Comment by vercellone** [comment]
False alarm.  I can't reproduce this since commit 4098afa (IPAddress comparison corrections).  Both can find a node by address alone.  Both default to searching the Common partition if -Name is specified and -Partition is not.

**Comment by vercellone** [comment]
Address and Name are both optional for Get-Node.

Test-Node currently requires one or the other but does not allow both.  Shouldn't it allow both?  And, assuming it should, can requiring at least one but allowing both be achieved with ParameterSets?

A run-time validation in the process block (since $Name allows ValueFromPipeline) is an option.

Any thoughts?

**Comment by joel74** [comment]
The only way I've envisioned to support an AND/OR for these two is with 3 parameter sets. Address is mandatory in set 1, Name in set 2, and both in set 3.

**Comment by vercellone** [comment]
I struggled with it yesterday.  But, just managed to get it working as follows:
```PowerShell
    [cmdletBinding(DefaultParameterSetName='Address')]
    param (
        $F5Session=$Script:F5Session,

        [Parameter(Mandatory,ParameterSetname='Address',ValueFromPipelineByPropertyName)]
        [Parameter(Mandatory,ParameterSetname='Both',ValueFromPipelineByPropertyName)]
        [PoshLTM.F5Address[]]$Address=[IPAddress]::Any,

        [Alias('ComputerName')]
        [Alias('NodeName')]
        [Parameter(Mandatory,ParameterSetname='Name',ValueFromPipeline,ValueFromPipelineByPropertyName)]
        [Parameter(Mandatory,ParameterSetname='Both',ValueFromPipeline,ValueFromPipelineByPropertyName)]
        [string[]]$Name='',

        [Parameter(ValueFromPipelineByPropertyName)]
        [string]$Partition
    )
```

I'll submit another PR after the F5Address PR is accepted, so my Test-Node changes can be considered independently.

**Comment by joel74** [comment]
Nicely done. Are you still looking for @drryu and/or @elijahgagne to review the route domain functionality in the F5Address PR before it's merged?

**Comment by elijahgagne** [comment]
Test-Node is working for me exactly as I would expect it to in every test I've thrown at it. 

Get-Node does not have the same parameter set definition, so you can do something with it that you can't with Test-Node: specify both a Name and Address. When I do that, I'm getting some unexpected results:

```
Get-Node -F5Session $F5Session `
         -Address "10.0.0.1" `
         -Partition "dev"
# Node is found

Get-Node -F5Session $F5Session `
         -Name "10.0.0.1" `
         -Partition "dev"
# Node is found

Get-Node -F5Session $F5Session `
         -Name "10.0.0.1" `
         -Address "10.0.0.1" `
         -Partition "dev"
# No output
```

Looking at the code, I see that it's finding the Node, but then the where clause is not matching on it. The where clause is returning false for: `"10.0.0.1" -contains "10.0.0.1%4"`

That made me wonder why the where clause returns true for my first test. In that case `"10.0.0.1" -contains "10.0.0.1"` was what went through the pipeline. All nodes in both the Common and dev partitions were returned and for some reason specifying an address with the %{partition} was not used. That makes next to no sense to me, but its what my LTMs are returning. 

One option that fixes things for me would be to make Name and Address be in different parameter sets like they are in Test-Node. Alternatively, the where clause could be updated to drop off the %{partition} when comparing IP addresses. Here's an update I tried in Get-Node and it fixes my issue:

```
Invoke-NullCoalescing {$JSON.items} {$JSON} |
    Where-Object { $Address -eq [IPAddress]::Any -or ([string[]]$Address) -contains ($_.address -Replace("%.*", ""))} |
    Add-ObjectDetail -TypeName 'PoshLTM.Node'
```

**Comment by vercellone** [comment]
@elijahgagne Did your testing include the latest commits to PR #128? If not, please get the latest and try again.

The intent is for you to be able to specify an -Address value that includes a route domain.  PoshLTM.F5Address facilitates that.  It does not change the behavior to include anything other than an exact address match.

Get-Node -Address '10.0.0.1' should NOT match a Node with address '10.0.0.1%4'.
Get-Node -Address '10.0.0.1%4' SHOULD match a Node with address '10.0.0.1%4'.

You should only see "10.0.0.1" -contains "10.0.0.1" if you have a node with that address without a route domain.

**Comment by elijahgagne** [comment]
I'm pretty sure I'm testing the correct code. I have downloaded POSH-LTM-Rest-a3e1fa913eda23845a421d82f1fe5c17440e1438.zip and imported it.

Here's some additional tests that don't seem like they produce the expected results to me

```
Get-Node -F5Session $F5Session `
         -Name "10.0.0.1" `
         -Partition "dev"
# Node is found

Get-Node -F5Session $F5Session `
         -Name "10.0.0.1" `
         -Address "10.0.0.1%4" `
         -Partition "dev"
# Node is found

Get-Node -F5Session $F5Session `
         -Address "10.0.0.1%4" `
         -Partition "dev"
# Node is not found and no output (e.g no 404)
```

Hopefully I'm not misunderstanding things, but what do you think of the following changes:
1) Make Name and Address be in different parameter sets like they are for Test-Node
2) Change the check for `$_.address` to be `($_.address -Replace("%.*", ""))` to cover both the cases where the LTMs return %{partition} and when they don't.

**Comment by elijahgagne** [comment]
Just to put a fine point on it, I am seeing that the 10.0.0.1 node sometimes has the address 10.0.0.1%4 and sometimes has the address 10.0.0.1. Which version of the address I get back depends on whether I've asked for only it or if I've asked for all nodes in a certain partition. Whenever I don't specify a Name, then I'm getting back all the nodes in the partition.

**Comment by vercellone** [comment]
1. $Partition is likely not being applied as expected in the absence of $Name.  But, I suspect that is a problem that existed prior to this PR.
1. It sounds to me like you have 2 distinct nodes.  1 with no route domain, and 1 with route domain 4.  From what I gather, no route domain is equivalent to route domain 0.  Is that not the case?

**Comment by elijahgagne** [comment]
In my examples, 10.0.0.1 is one distinct node. The LTM will show it's address as 10.0.0.1 if search by Name or 10.0.0.1%4 if I don't specify a Name. It does seem very unexpected to me that the LTM would list the same node with different addresses depending on how you query for it, but that is what I'm seeing.

**Comment by vercellone** [comment]
I can't reproduce this with a3e1fa9.  I tried all of the tests you demonstrated and all returned the desired node successfully (address = 10.200.26.23%1).

What is the result of the following command for you?  If nothing, what is the result without the Where-Object filter?
```PowerShell
Get-Node -F5Session $F5Session `
         -Partition "dev" |
         Where-Object { $_.address -like '10.0.0.1*' }
```

**Comment by elijahgagne** [comment]
That command does produce results for me with the where clause. Here's to full output with a second example showing the output when -Name is specified.

```
PS C:\Users\egagn> Get-Node -F5Session $F5Session `
>>          -Partition "dev" |
>>          Where-Object { $_.address -like '10.0.0.1*' }

Name         Partition Address      Description
----         --------- -------      -----------
10.0.0.1     dev       10.0.0.1


PS C:\Users\egagn>
PS C:\Users\egagn> Get-Node -F5Session $F5Session `
>>          -Partition "dev" `
>>          -Name '10.0.0.1' |
>>          Where-Object { $_.address -like '10.0.0.1*' }

Name         Partition Address        Description
----         --------- -------        -----------
10.0.0.1     dev       10.0.0.1%4
```

**Comment by vercellone** [comment]
That is almost certainly a difference in the filters applied on the server (F5 device).  Without -Name, "?`$filter=partition eq $Partition" would be appended to the Uri.  With -Name "\~$Partition\~$Name" would be appended to the Uri.

Things I would check next:
1. Compare the objects returned by the 2 commands above.  (hint: use Compare-Object and/or Select-Object *).  Is either associated with an application?  Are there any other differences?
1. Compare nodes returned by Get-Node vs. nodes listed by other means (UI, tmsh).  Compare both all nodes and 'dev' partition nodes, looking for any oddities.  Which lists 10.0.0.1, 10.0.0.1%4, or both?

**Comment by elijahgagne** [comment]
1) I couldn't easily get Compare-Object to work, but it was easy enough to compare by hand. The only difference is the address attribute. See below.
2) In the web interface, nodes that also exist in the Common partition show up as 10.0.0.2%0. 10.0.0.1 does not exist in the Common partition, so it only shows as 10.0.0.1 everywhere I look in the web interface. Interestingly, 10.0.0.1 also exists in the admin partition. So it is possible that this has something to do with needing to distinguish itself from the node with the same IP address in a different partition other than Common. I can do more testing on that tonight. 
```
PS C:\Users\egagn> $a = Get-Node -F5Session $F5Session `
         -Partition "dev" |
         Where-Object { $_.address -like '10.0.0.1*' }
PS C:\Users\egagn>
PS C:\Users\egagn> $b = Get-Node -F5Session $F5Session `
         -Partition "dev" `
         -Name '10.0.0.1' |
         Where-Object { $_.address -like '10.0.0.1*' }
PS C:\Users\egagn> $a | fl


kind            : tm:ltm:node:nodestate
name            : 10.0.0.1
partition       : dev
fullPath        : /dev/10.0.0.1
generation      : 1
selfLink        : https://localhost/mgmt/tm/ltm/node/~dev~10.0.0.1?ver=11.6.1
address         : 10.0.0.1
connectionLimit : 0
dynamicRatio    : 1
ephemeral       : false
fqdn            : @{addressFamily=ipv4; autopopulate=disabled; downInterval=5; interval=3600}
logging         : disabled
monitor         : default
rateLimit       : disabled
ratio           : 1
session         : monitor-enabled
state           : up



PS C:\Users\egagn> $b | fl


kind            : tm:ltm:node:nodestate
name            : 10.0.0.1
partition       : dev
fullPath        : /dev/10.0.0.1
generation      : 1
selfLink        : https://localhost/mgmt/tm/ltm/node/~dev~10.0.0.1?ver=11.6.1
address         : 10.0.0.1%4
connectionLimit : 0
dynamicRatio    : 1
ephemeral       : false
fqdn            : @{addressFamily=ipv4; autopopulate=disabled; downInterval=5; interval=3600}
logging         : disabled
monitor         : default
rateLimit       : disabled
ratio           : 1
session         : monitor-enabled
state           : up



PS C:\Users\egagn>
```

**Comment by vercellone** [comment]
I bet your 'dev' partition's default route domain is set to 4.

**Comment by elijahgagne** [comment]
Indeed it is.

**Comment by vercellone** [comment]
That explains it.  Given that, Get-Node is working as designed.  Thanks for taking the time to report this and work through it.

A PR for Test-Node to allow Address, Name, or both will be submitted later.  Do you have any outstanding Get/Test-Node issues?

Also, have you had a chance to test out *-VirtualServer and/or *-PoolMember for elements involving a route domain?  Either way, I'd appreciate relevant feedback on #127 before recommending @joel74 commit #128.

**Comment by vercellone** [comment]
This result is still unsettling, huh?
```PowerShell
Get-Node -F5Session $F5Session `
         -Name "10.0.0.1" `
         -Address "10.0.0.1" `
         -Partition "dev"
# No output
```
Although -like '10.0.0.1*' works in your environment, I think it is too greedy as a rule.  The best improvement would be to factor in the partition's default route domain.
```PowerShell
Where-Object { $Address -eq [IPAddress]::Any -or ([string[]]$Address) -contains $_.address -or ([string[]]$Address) -contains ('{0}%{1}' -f $_.address,$DefaultRouteDomain}
```
But, then we need to retrieve the $DefaultRouteDomain per partition before applying the Where-Object.  What do you think?  Have you got a better idea?

**Comment by elijahgagne** [comment]
Yeah, I don't like having to retrieve the DefaultRouteDomain. Instead of `-like '10.0.0.1*'` what about `($_.address -Replace("%.*", ""))`. That will drop off the route domain and match on just the IP address, which matches my expectations. 

I have not done any testing of *-VirtualServer and/or *-PoolMember so I'll that now and follow up shortly.

**Comment by elijahgagne** [comment]
*-VirtualServer passed every test I could think of. The LTMs correctly produce a HTTP 400 if I try to create a virtual server in a partition without the correct route domain. If I leave off the route domain, everything works as expected as well. 

Similar to Get-Node, I have some unexpected results for Get-PoolMember and Get-PoolsForMember. But whatever we do for Get-Node should solve these also. 

```
Get-PoolMember -F5Session $F5Session `
               -PoolName "ewg-iapp-443_pool" `
               -Application "ewg-iapp-443" `
               -Partition "dev" `
               -Address "10.0.0.1" `
               -Name "10.0.0.1"
# No output
Get-PoolMember -F5Session $F5Session `
               -PoolName "ewg-iapp-443_pool" `
               -Application "ewg-iapp-443" `
               -Partition "dev" `
               -Address "10.0.0.1%4" `
               -Name "10.0.0.1"
# Desired output, but not sure I like having to list the address like that


Get-PoolsForMember -F5Session $F5Session -Address "10.0.0.1"
# No output
Get-PoolsForMember -F5Session $F5Session -Address "10.0.0.1%4"
# Desired output
```

It looks like [PoshLTM.F5Address] is in the following functions (which surprised me because that wasn't obvious to me in the commit diff). 

```
Get-Node
Test-Node
New-Node
Enable-Node
Remove-Node
Disable-Node

New-VirtualServer
Set-VirtualServer

Get-PoolMember
Add-PoolMember
Disable-PoolMember
Enable-PoolMember
Remove-PoolMember

Get-PoolMemberStats
Get-PoolsForMember

Set-PoolMemberDescription
```

I can test more of these if that would be helpful. If I should test more, I'm feeling that I need to invest some time in setting up a more proper suite of tests to make this more efficient.

**Comment by vercellone** [comment]
Re: ($_.address -Replace("%.*", ""))

Perhaps I'm missing something, but doesn't that defeat the purpose of allowing an $Address parameter with a route domain?

I have a counter-offer: How about if $Address.RouteDomain has value, the comparison includes the route domain on both sides.  If not, the comparison is based solely on the IPAddress portion (ignoring route domain).

So, you should get your expected result whether you supply -Address 10.0.0.1 or -Address 10.0.0.1%4, but -Address 10.0.0.1%3 would return nothing.

**Comment by vercellone** [comment]
All testing is appreciated, but you've already completed more than I expected.

**Comment by elijahgagne** [comment]
Bingo, your counter offer sounds like the right solution to me. Thanks for putting the effort into getting this right. I think this is going to add a lot of value for me.
