### ISSUE TITLE
Proposed change to Get-F5Session

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#13]
I've been asked by the PowerShell Gallery people to update the params on this functions, so it takes a PSCredential object instead of a username and password. I'm fine with doing this, but it'd be a breaking change, so I wanted to post it here first, to see if anyone minded.

**Comment by joel74** [comment]
If there are no comments on this issue by EOD Friday (12/11), I'll go ahead with the change.
Thanks.

**Comment by dsolodow** [comment]
Sounds like a good idea; might need to have some code to strip off the domain name from the credential object before passing it. Not sure if the REST API processes it properly, but I know the native iControl cmdlets need it stripped.

**Comment by joel74** [comment]
Thanks for the feedback, Damien. I've tried this out and it seems to work fine to just put the username in the credential object, with no domain value, and use that. Are you saying the domain name is getting added automatically to the credential object?
Thanks, Joel

**Comment by dsolodow** [comment]
No, the domain name doesn't get added to the cred object, but if you're using an existing credential object that does have the domain name, it may cause issues.

**Comment by joel74** [comment]
I guess so, but I'd imagine people would create a specific credential object just for working with the LTM. I went ahead and made the update, and included some info on how to create the credential object programmatically. If you get a chance to test it, let me know if it works fine or if you run into any issues. Thanks.
