### ISSUE TITLE
NewPool not passing Portnumber correctly

### ISSUE THREAD

**Issue by LKlein75** [joel74/POSH-LTM-Rest#134]
Hi Joel
Tried to post this on F5 devcentral, but my comment was marked being spam, so excuse me if this maybe isn't exactly the right place.  It might be just my lack of powershell skills of not typecasting or quoting the portnumber right. 

Looking at the example 

    .EXAMPLE
        New-Pool -F5Session $F5Session -PoolName "MyPoolName" -MemberDefinitionList @("Server1,80,Web server","Server2,443,Another web server")
        
I've done this:

`New-Pool -PoolName "lKtSTpOOL" -LoadBalancingMode least-sessions -MemberDefinitionList @("10.25.10.1,443,Firewall 1")`

Which gives me this result:

    Add-PoolMember : Cannot process argument transformation on parameter 'PortNumber'. Cannot convert the "System.Object[]" value of 
    type "System.Object[]" to type "System.Int32".
    At C:\Users\admme\Documents\WindowsPowerShell\Modules\F5-LTM\Public\New-Pool.ps1:54 char:131
    + ...  -Partition $Partition -Address $Node -PortNumber $PortNumber -Status ...
    +                                                       ~~~~~~~~~~~
        + CategoryInfo          : InvalidData: (:) [Add-PoolMember], ParameterBindingArgumentTransformationException
        + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-PoolMember

Splitting the commands does work

`new-pool -PoolName "lKtSTpOOL" -LoadBalancingMode least-sessions`

`Add-PoolMember -PoolName "lKtSTpOOL" -Address 10.25.10.1 -PortNumber 443 -Description "Firewall 1"`

Thanks ahead

**Comment by joel74** [comment]
Thanks. PR #135 will fix this.

**Comment by joel74** [comment]
PR #135 merged. Please confirm this is fixed for you. Thanks.

**Comment by joel74** [comment]
Good catch. It looks like the Add-PoolMember function, though accepting a description, isn't properly setting it. I'll take a look.

**Comment by joel74** [comment]
I committed a fix to my branch. I'm giving my previous pull request for adding support for FQDNs a little time for folks to review, and then I'll create a pull request for this fix.

**Comment by joel74** [comment]
LKlein75. please test again when you get a chance and let me know if this issue can be closed. Thanks.

**Comment by LKlein75** [comment]
I can confirm description now also works. Have a good weekend :+1:
