### ISSUE TITLE
Create pool with already existing node?

### ISSUE THREAD

**Issue by mtengmo** [joel74/POSH-LTM-Rest#146]
Is it possible to create a pool with already created node?
I got issue to create the node with pool command, because of partitions. The node will be created in Common partition using fqdn. And Autopopulate is enabled. 

new-node -Name "/partition/website.azurewebsites.net_pool_paas" -FQDN "website.azurewebsites.net" -Partition partition -AddressType ipv4 -AutoPopulate disabled

New-Pool -Name "/partition/website.azurewebsites.net_pool_paas" -Partition partition -MemberDefinitionList "/partition/website.azurewebsites.net_pool_paas:443" -LoadBalancingMode round-robin

Add-PoolMember : Cannot process argument transformation on parameter 'Address'. Cannot convert value "/partition/website.azurewebsites.net_pool_paas:44" to type "PoshLTM.F5Address". Error: "No such host is know
At C:\Program Files\WindowsPowerShell\Modules\f5-ltm\1.4.207\Public\New-Pool.ps1:60 char:117
+ ... 5Session -PoolName $Name -Partition $Partition -Address $Node -PortNu ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-PoolMember], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-PoolMember

**Comment by joel74** [comment]
PR #148 has been submitted. @mtengmo , if you're able to test these changes and let me know the results, that'd be great. Thanks.

**Comment by joel74** [comment]
Fixed with the merge of PR #148
