### ISSUE TITLE
401 F5 Authorization token not exists

### ISSUE THREAD

**Issue by mtengmo** [joel74/POSH-LTM-Rest#147]
I got this issue after around 1h, not sure if it´s related to I already got a WebGUI connection at the same time? 
 
New-F5Session -LTMName $MyLTM_IP -LTMCredentials $MyLTMCreds

 get-pool -Partition paas

Invoke-F5RestMethod : "401 F5 Authorization Required: X-F5-Auth-Token does not exist.
At C:\Program Files\WindowsPowerShell\Modules\f5-ltm\1.4.207\Public\Get-Pool.ps1:32 char:21
+ ...     $JSON = Invoke-F5RestMethod -Method Get -Uri $URI -F5Session $F5S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-F5RestMethod

**Comment by joel74** [comment]
If you leave the session life at the default, the token will only be good for 20 minutes. You can override this by passing in a value for TokenLifespan as high as 36000, which gives the token a life of 10 hours.
