### ISSUE TITLE
Support partitions other than 'Common'

### ISSUE THREAD

**Issue by vercellone** [joel74/POSH-LTM-Rest#15]
I need to be able to manage 'Common','Development', and 'Production' partitions.  Could either expose a $Partition param where applicable or add a Partition property to the session.

**Comment by joel74** [comment]
Good idea. The session property route would be simpler, but I'm not sure that's the better way. 
I think my preference would be to make it a non-mandatory param when applicable that defaults to 'Common' and can be overwritten as needed. That shouldn't be too difficult to knock out.

**Comment by joel74** [comment]
Vercellone, could you do me a favor and post some sample URL endpoints for virtual servers and pool members not in the 'common' partition? For example, in constructing the endpoint needed to get a pool member, 'Common' is references twice. i.e. ...pool/~Common~$PoolName/members/~Common~$IPAddress
Since I only have a 'Common' partition, I don't know if both 'Common' references are for the 'Common' partition. Thanks.

**Comment by vercellone** [comment]
Unfortunately, our ircd (Rest API) service does not appear to be started, and I don't have terminal access to start it myself.  I'll have to convince the infrastructure guys to start it for me.  I'll keep you posted.

Also note that we are running version 11.5.1 Build 8.0.175 Hotfix HF8.

**Comment by joel74** [comment]
Thanks. In the meantime, I'll post something on devcentral and see if I can get an answer to my question that way as well.

**Comment by dsolodow** [comment]
My F5 LTM (12.0 HF1) is queryable via REST, so I can probably get you the endpoint info you need.

Unfortunately my brain is a bit foggy on how to do that; would it be via tmsh or a GET?

**Comment by joel74** [comment]
Thanks, Damien. This would be a GET, something in the format of:
https://hostname/mgmt/tm/ltm/pool/~Common~(PoolName)/members/~Common~(memberaddress)
where the Common partition references are replaced by the custom partition name.
You could just start at the /pool/ level in a browser and explore that way as well.
Cheers.

**Comment by dsolodow** [comment]
Looks like:
https://hostname/mgmt/tm/ltm/pool/~(PartitionName)~(iAppName)/members/~(PartitionName)~(memberaddress)

**Comment by joel74** [comment]
Thanks. So iAppName instead of PoolName? That's interesting. I think that's because the pool you looked at was created with an iApp. Is that corrrect?

**Comment by vercellone** [comment]
This is working for me:
```PowerShell
function Get-Pool {
    param (
        [Parameter(Mandatory=$true)]$F5session,
        [Parameter(Mandatory=$false)][string]$Partition='Common',
        [Parameter(Mandatory=$true)][string]$PoolName
    )

    Write-Verbose "NB: Pool names are case-specific."

    #Build the URI for this pool
    $URI = $F5session.BaseURL + "pool/~$Partition~$PoolName"

    Try {
        Invoke-RestMethodOverride -Method Get -Uri $URI -Credential $F5session.Credential -ErrorAction SilentlyContinue
    }
    Catch{
        Write-Error ("Failed to get the $Partition $PoolName pool.")
        Write-Error ("StatusCode:" + $_.Exception.Response.StatusCode.value__)
        Write-Error ("StatusDescription:" + $_.Exception.Response.StatusDescription)
    }
}
function Get-PoolMember {
    param(
        [Parameter(Mandatory=$true)]$F5session,
        [Parameter(Mandatory=$true)]$ComputerName,
        [Parameter(Mandatory=$false)]$Partition='Common',
        [Parameter(Mandatory=$true)]$PoolName
    )

    $PoolMember = $null

    $IPAddress = Get-PoolMemberIP -F5Session $F5session -ComputerName $ComputerName -Partition $Partition -PoolName $PoolName

    $PoolMemberURI = $F5session.BaseURL + "pool/~$Partition~$PoolName/members/~$Partition~$IPAddress`?"

    Try {
        $PoolMemberJSON = Invoke-RestMethodOverride -Method Get -Uri $PoolMemberURI -Credential $F5session.Credential
        $PoolMemberJSON
    }
    Catch {
        Write-Error "Failed to get the details for the pool member $ComputerName in the $PoolName pool."
        Write-Error ("StatusCode:" + $_.Exception.Response.StatusCode.value__)
        Write-Error ("StatusDescription:" + $_.Exception.Response.StatusDescription)
    }
    
    $PoolMember
}
function Get-PoolMemberIP {
    param(
        [Parameter(Mandatory=$true)]$F5Session,
        [Parameter(Mandatory=$true)]$ComputerName,
        [Parameter(Mandatory=$false)]$Partition='Common',
        [Parameter(Mandatory=$true)]$PoolName
    )

    $IPAddress = Get-CimInstance -ComputerName $ComputerName -Class Win32_NetworkAdapterConfiguration -ErrorAction SilentlyContinue | Where-Object DefaultIPGateway | Select-Object -exp IPaddress | Select-Object -first 1
    #If we don't get an IP address for the computer, then fail
    If (!($IPAddress)){
        Write-Error "Failed to obtain IP address for $ComputerName. The error returned was:`r`n$Error[0]"
        Return($false)
    }

    #Check the members of the specified pool to see if there is a member that matches this computer's IP address
    $PoolMembers = Get-PoolMemberCollection -PoolName $PoolName -Partition $Partition -F5session $F5Session     
    $MemberName = $false
    foreach($PoolMember in $PoolMembers) {
        if($PoolMember.address -eq $IPAddress) {
            $MemberName = $PoolMember.Name
        }
    }

    If ($MemberName){
        Return($MemberName)
    }
    Else {
        Write-Error "This computer was not found in the specified pool."
        Return($false)
    }
}
function Get-PoolMemberCollection {
    param(
        [Parameter(Mandatory=$true)]$F5session,
        [Parameter(Mandatory=$false)]$Partition='Common',
        [Parameter(Mandatory=$true)]$PoolName
    )

    $PoolMembersPage = $F5session.BaseURL + "pool/~$Partition~$PoolName/members/?"

    Try {
        $PoolMembersJSON = Invoke-RestMethodOverride -Method Get -Uri $PoolMembersPage -Credential $F5session.Credential
        $PoolMembersJSON.items
    }
    Catch {
        Write-Error "Failed to get the members of the $PoolName pool."
        Write-Error ("StatusCode:" + $_.Exception.Response.StatusCode.value__)
        Write-Error ("StatusDescription:" + $_.Exception.Response.StatusDescription)
    }
}
```

**Comment by joel74** [comment]
Great! Then I'll try that in all the functions that reference the 'Common' partition, and if we run into an issue with iApp-spawned pools / virtual servers, we'll jump off that bridge then.

**Comment by joel74** [comment]
Ok - functions updated (I believe it was 13 of them), and internal functionality function passed for using defaults. Let me know if you have any issues when passing in an alternate partition name, since I'm not able to test that. Cheers.
