### ISSUE TITLE
Issue to Install module

### ISSUE THREAD

**Issue by michalss** [joel74/POSH-LTM-Rest#151]
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'F5-BIGIP'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.0\PSModule.psm1:2057 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by joel74** [comment]
Hi,
It seems like you're attempting to use Package Management to install the F5-BIGIP module, which is a different module than the one in this repo, and which not currently available in the PowershellGallery. If you want to use the F5-BIGIP module, I'd suggest just downloading the archive from the repo.

**Comment by joel74** [comment]
Please let me know if you still have any issues I can help with. Thanks.

**Comment by joel74** [comment]
Closing. Please reopen if you have issues downloading and using the F5-BIGIP module. Thanks.
