### ISSUE TITLE
call to get pool member connections returns no value

### ISSUE THREAD

**Issue by bootz52** [joel74/POSH-LTM-Rest#154]
Get-PoolMemberStats | Select-Object -ExpandProperty 'serverside.curConns' returns no value same with version 12.1.2

"However, this may no longer work as of v12.1" Per Joel 20171031

BIG-IP 12.1.2

**Comment by joel74** [comment]
Hi, bootz52. Can you please include the full command you're using / the object you're passing to Get-PoolMemberStats? When I call Get-PoolMember and pass the returned object to Get-PoolMemberStats on LTM 12.1, it gives me back the current connection count using the code you specified. Thanks.

**Comment by joel74** [comment]
Closing based on the assumption that the issue is resolved. Please reopen and provide additional details if it is not. Thanks.

**Comment by Ze1ro** [comment]
Hello Joel,
The chain goes as follows;
$Pool = Get-Pool -F5Session $F5Session -Name "F5-PoolName" //This returns the proper pool
$PoolMember = Get-PoolMember -F5Session $F5Session -InputObject $Pool //This returns the members properly. In this case, it returns two members.
Get-PoolMemberStats -F5Session $F5Session -InputObject $PoolMember //returns nothing. No errors or data
I hope this helps

**Comment by joel74** [comment]
Hi, Ze1ro,
I tested the exact snippet you gave me against the latest version of the module connecting to LTMs v 11.6, 12.1 and 13.0, and they all gave me results. What version LTM are you connecting to?

**Comment by Ze1ro** [comment]
I reinstalled the module for the PS gallery and all appears to be working now.
Thank you for taking the time to troubleshoot.

**Comment by joel74** [comment]
Glad to hear it's resolved. Maybe that will fix it for bootz52 as well.

**Comment by bootz52** [comment]
Worked for me as well. Thanks for your help.

**Comment by joel74** [comment]
Glad to hear it, bootz52.
