### ISSUE TITLE
Add -PortNumber to Remove-PoolMember

### ISSUE THREAD

**Issue by Ben1492** [joel74/POSH-LTM-Rest#156]
We have some pools that use different ports on the same  servers (mostly WebSphere JVMs).  It would be nice to be able to remove them bases on IP and Port.   Right now the commandlet removes all the members with the same IP.

**Comment by vercellone** [comment]
Have you tried the following?

```PowerShell
Remove-PoolMember -Name "Server:Port" 
```

**Comment by joel74** [comment]
I just tested and it attempted to remove all matching IPs, ignoring the port specified. I guess further investigation is required.

**Comment by joel74** [comment]
I'm not sure why it didn't work with my first test, but now it works fine. I ran multiple attempts and they worked consistently, so I'm considering this issue resolved.
