### ISSUE TITLE
Sync-Configuration

### ISSUE THREAD

**Issue by vercellone** [joel74/POSH-LTM-Rest#16]
We use active/standby pairs and would need to be able to [sync the config](https://devcentral.f5.com/questions/rest-api-and-config-sync-question).

```PowerShell
Invoke-RestMethod -Method Post -Uri "https://$LTMName/mgmt/tm/cm" -Credential $Credential -Body: @{
    command='run'
    utilCmdArgs="config-sync to-group $GroupName"
} -Headers $Headers -ContentType 'application/json'
````

**Comment by joel74** [comment]
added a new function called Sync-DeviceToGroup. It takes an F5 session and a group name
