### ISSUE TITLE
Creating new Modules

### ISSUE THREAD

**Issue by kleinsmk** [joel74/POSH-LTM-Rest#164]
I've been trying to get them to utilize the New-Session function with some other functions I've built.  This way others can just run automation scripts I've written without fussing with two sets on connections.

Attempting to pass in $F5Session=$Script:F5Session that I've seen in the other built in other functions in the modules, but it ends up null.

Could you possibly elaborate a bit on how the other functions you wrote seem to be able to find the session by default?

**Comment by elijahgagne** [comment]
I would point you at [Get-Pool](https://github.com/joel74/POSH-LTM-Rest/blob/master/F5-LTM/Public/Get-Pool.ps1) as a random function to inspect. `$F5Session` is not a variable that is passed into the function. `$Script:F5Session` means that the variable is available anywhere in the module. As such, you can simply use it (without needing to qualify it with `$Script:`) as follows:

https://github.com/joel74/POSH-LTM-Rest/blob/f1d826521ff3fc982e91812ae010e34c718373d3/F5-LTM/Public/Get-Pool.ps1#L32

Hope that helps.

**Comment by kleinsmk** [comment]
Thanks! I think you gave me what I needed.  I'd gather script scope isn't wide enough for functions that I would end my writing itself it looks like as they won't be part of the module.  So maybe modify this to be global?  Do you by chance have a good reference on how to add functions to an existing module?  I'm not a programmer by trade if it didn't already show!

**Comment by joel74** [comment]
Hi, I'd suggest having New-Session return the created session object (using the -passthrough flag). You can store that object in a local variable and set a variable in the global scope to use the value as well.

I.e.
$Global:F5Session = New-F5Session -LTMName myLTM -LTMCredentials $credsObj -Default -PassThru

**Comment by kleinsmk** [comment]
Thanks Joel.  The simple answer FTW.
