### ISSUE TITLE
Non-standard parameter names in 

### ISSUE THREAD

**Issue by jordanmills** [joel74/POSH-LTM-Rest#165]
Parameter names in New-F5Session don't conform to standard cmdlet parameter names (https://docs.microsoft.com/en-us/powershell/developer/cmdlet/standard-cmdlet-parameter-names-and-types) and might be counterintuitive to new users of the module.   Basically $LTMCredentials should be $Credential and $LTMName should be $Name.   The former prevents doing a simple find-replace, as $Credential is used later.  Also, aliases might be added to make sure that this change would not break existing scripts.  This leads to a choice of changing the parameter names in F5-LTM.tests.ps1, but a simple find/replace seems to work there.

I implemented all of this locally but I'm not sure if I should try to push changes.

**Comment by joel74** [comment]
Hi Jordan,
Thanks. If you want, you can make a pull request with the work you've done, so it can be reviewed and discussed.

Thanks,
Joel

**Comment by joel74** [comment]
Hi, Jordan,
I'm happy to review the changes if you make a pull request. 
Thanks,
Joel

**Comment by joel74** [comment]
Closing - inactive.
