### ISSUE TITLE
Disable-Node in PoolMember pipeline

### ISSUE THREAD

**Issue by neilcowlin** [joel74/POSH-LTM-Rest#169]
Hi guys,

Thank you so much for this great module.

My issue is regarding the behaviour of` Disable-Node` in pool based pipelines where it seems to behave instead like `Disable-PoolMember`.  It doesn't seem to behave quite as I'd expect.

I could be misinterpreting something though.

`Disable-Node -node node1`
This behaves exactly as I'd expect - disabling the node object.

`Get-PoolMember -PoolName pool1 | Disable-Node`
This instead behaves exactly like
`Get-PoolMember -PoolName pool1 | Disable-PoolMember`
Only the Pool Member is disabled, the node object (and therefore its use in other pools) is unaffected.  This isn't what I would expect regardless of what is being passed to it.

E.g.

```

Get-PoolMember -PoolName pool1
Name     Partition Address        Description Monitor Session      State
----     --------- -------        ----------- ------- -------      -----
node1:80 Common    192.168.202.10             default user-enabled unchecked
node2:80 Common    192.168.202.20             default user-enabled unchecked

Get-PoolMember -PoolName pool2

Name      Partition Address        Description Monitor Session      State
----      --------- -------        ----------- ------- -------      -----
node1:443 Common    192.168.202.10             default user-enabled unchecked
node2:443 Common    192.168.202.20             default user-enabled unchecked

Get-Node | Select-Object Name, Address, Session

name  address        session
----  -------        -------
node1 192.168.202.10 user-enabled
node2 192.168.202.20 user-enabled

### Try to disable nodes - but this instead behaves like piping into Disable-PoolMember would

Get-PoolMember -PoolName pool1 | Disable-Node                                                                                                                                         True
True

Get-PoolMember -PoolName pool1

Name     Partition Address        Description Monitor Session       State
----     --------- -------        ----------- ------- -------       -----
node1:80 Common    192.168.202.10             default user-disabled unchecked
node2:80 Common    192.168.202.20             default user-disabled unchecked

Get-PoolMember -PoolName pool2

Name      Partition Address        Description Monitor Session      State
----      --------- -------        ----------- ------- -------      -----
node1:443 Common    192.168.202.10             default user-enabled unchecked
node2:443 Common    192.168.202.20             default user-enabled unchecked

Get-Node | Select-Object Name, Address, Session

name  address        session
----  -------        -------
node1 192.168.202.10 user-enabled
node2 192.168.202.20 user-enabled

### Actually disable the node

Disable-Node -Name node1                                                                                                                                                              True

Get-Node | Select-Object Name, Address, Session

name  address        session
----  -------        -------
node1 192.168.202.10 user-disabled
node2 192.168.202.20 user-enabled

```

Thanks for reading through that!  My PS skills aren't quite there yet to create a PR, but I'll see what I can do, assuming I haven't just invented this as an issue.

**Comment by joel74** [comment]
Hi, as you surmised, the Disable-Node function isn't distinguishing between node objects and pool member objects. It simply attempts to set the state for the object passed in to Disabled. One resolution for this would be to reject objects that aren't nodes that get passed to the function. I think this would be the best solution, though I don't think that helps you. I wouldn't expect an associated node to get disabled if I passed in a pool member, though.

**Comment by joel74** [comment]
Closing this issue due to lack of reasons given for work needed to identify object passed as a node.
