### ISSUE TITLE
Error when attempting to add profile to virtual server

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#173]
From the log:
pid=11420 user=admin folder=/Common module=(tmos)# status=[Syntax Error: one or more configuration identifiers must be provided] cmd_data=modify ltm virtual /Common/test { address-status yes auto-lasthop default cmp-enabled yes connection-limit 0 description "test server" destination /Common/10.186.10.136:80 enabled gtm-score 0 ip-protocol tcp mask 255.255.255.255 mirror disabled mobile-app-tunnel disabled nat64 disabled policies replace-all-with {:

**Comment by tmccarthy349** [comment]
I think I got it. I removed the module from my computer and reinstalled it. It seems to be working now, I was able to add the http, and the Ascend_HTTP in 2 separate attempts. Will continue to test and relate any issues I run into.

**Comment by joel74** [comment]
Excellent. I'm glad to hear you've made progress, Tim. Do let me know if you run into anything else. I'll leave this issue open for a week or so. Thanks.

**Comment by tmccarthy349** [comment]
Thanks for all your help Joel! Just as a FYI though, I think I did find a typo in your example. You have the following.
$vs | Add-Member 'fallbackPersistence' -Value 'source_addr'
I believe it should be
$vs | Add-Member -Name 'fallbackPersistence' -Value 'source_addr' -MemberType NoteProperty

**Comment by joel74** [comment]
Thanks for noting those typos. I'll update the example.

**Comment by tmccarthy349** [comment]
One last question, I have everything working in the script with the exception of the log profiles. I've set it manually and examind the contents of $vs.profiles, but don't see them there. Any idea where they are stored and if they can be set?

**Comment by joel74** [comment]
I'm not really sure. My suggestion would be to post that question on DevCentral and see if it grabs the attention of a profile expert.

**Comment by tmccarthy349** [comment]
Thanks Joel, I've added it today. It's really weird thoguh, I can see it under security-log-profiles in bigip.conf, however when I pull the config down using $vs = Get-VirtualServer then echo $vs.security-log-profiles it has nothing listed, but it does have the information I would expect under $vs.securitylogprofiles.  I go ahead and manipulate it at that location, then send it back to the F5, and it doesn't show up.

**Comment by joel74** [comment]
Interesting, Tim. I don't recall - did you tell me what version of the LTM you're using? 
I believe the securityLogProfiles is a separate property from the profilesReference subcollection, and the PS module doesn't explicitly define the securityLogProfiles value of a virtual server (yet). There are actually a lot of VS properties that aren't yet defined - I tried to just do the most popular ones and add on as requested.
