### ISSUE TITLE
Sync-DeviceToGroup issues

### ISSUE THREAD

**Issue by maxpowerbjh** [joel74/POSH-LTM-Rest#178]
Trying to use the Sync-DeviceToGroup function and getting an error.  In the function I had to remove the -ErrorMessage and -AsBoolean parameters in order to find the real error. I'd guess that it has something to do with the dashes in the utilCmdArgs  but I haven't been able to find a way around it yet.  Here is the $JSONBody variable as it exists in the function now. 
$JSONBody = @{command='run';utilCmdArgs="config-sync to-group $GroupName"}

Invoke-F5RestMethod : "400 Bad Request: "config-sync" unexpected argument
At C:\Program Files\WindowsPowerShell\Modules\F5-LTM\Public\Sync-DeviceToGroup.ps1:20 char:5
Invoke-F5RestMethod -Method POST -Uri "$URI" -F5Session $F5Session -Body $JS ...
CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-F5RestMethod

**Comment by joel74** [comment]
Hi, maxpowerbjh, can you let me know what version you're using? I only have a HA pair using 12.1 that I can test with, and it works there. Thanks.

**Comment by maxpowerbjh** [comment]
Anyone else out there using v13 that could give it a try?

**Comment by kleinsmk** [comment]
Can confirm Sync Device to group works on 13.x as I use it daily.  

`Invoke-F5RestMethod : "400 Bad Request: "config-sync" unexpected argument`

Generally that error might be a random parameter is being passed.  

Usage is like Sync-DeviceToGroup -Groupname "sync group name from the f5 gui"

**Comment by joel74** [comment]
I'm curious what shows in the Audit log for the failed sync. This is what I see in the audit log on my 12.1 pair:
pid=XXXX user=XXXX folder=/Common module=(tmos)# status=[Command OK] cmd_data=run cm config-sync to-group device-group-failover-f6263dfa915a

**Comment by maxpowerbjh** [comment]
Good grief.  Apparently you also get this message when the account you are using doesn't have permissions to do a sync.  My script normally runs as service account.  Once I tried it with my account, which does have sync permissions, it ran beautifully.  Sorry to have wasted your time.

**Comment by joel74** [comment]
No worries. I'm glad to hear things didn't break with v13.
