### ISSUE TITLE
Add-PoolMember + Remove-PoolMember assume name=[IPAddress]:[Port]

### ISSUE THREAD

**Issue by vercellone** [joel74/POSH-LTM-Rest#18]
All of our pool members are named [ComputerName]:[Port].  While I agree that putting the Computername in the description is probably a better practice, renaming the objects isn't practical at this time.

**Comment by joel74** [comment]
That's a good point. I'd actually made myself a note a few weeks back to alternatively accept [Computername]:[Port], but didn't work on it as the demand wasn't there. Now apparently it is. :) I'd like to set this up as two different param sets. It should be straight-forward.

**Comment by joel74** [comment]
It looks like, if we're looking up pool members by FQDN, we'll need to filter out the members where ephemeral is true. Adding a pool member using the FQDN option causes a second system-managed pool member using the IP address for that FQDN.

**Comment by vercellone** [comment]
I'll have to experiment with this myself.  First guess for maximum flexibility would be to use $select={link,selfLink}&filter=address eq $IPAddress query request(s) to identify existing members/nodes and use the resulting links rather than trying to use several parametersetnames and all the conditional logic that would require.  So, if an existing member/node is identified by address, ignore the name parameter value.

I've actually been entertaining the idea of using this strategy in other places to introduce simple pipeline support.  I suspect it would prove more efficient and reliable to pass around object links resulting from filtered queries than to derive the links from name/partition inputs.

**Comment by joel74** [comment]
I think I've got a handle on how this will work, based on your idea. The gist, as I understand it, is:
1) Pass in computer name
2) Retrieve IP address from computer
3) Retrieve membername from selfLink based on IP address value
4) Query API using membername and return member JSON.

However, I noticed when working with the new \Public files that the encoding has changed on them, and they're no longer searchable, at least using the command line tool findstr, so it's not easy to see all the places Get-PoolMemberIP is referenced. Is there a benefit to encoding the files as Little Endian, (vs. Big Endian vs. UTF-8 vs ANSI)?

**Comment by vercellone** [comment]
The encoding is my fault.  The script I used to extract the functions used Out-File with the default encoding.  I created an issue, fixed both of my branches, and initiated pull request #22 to fix.

As for Get-PoolMember, my work in progress involves an Address parameter:
```PowerShell
        [Parameter(Mandatory=$false)]
        [Alias("ComputerName")]
        [string]$Address
```
which is conditionally converted to an IpAddress as needed:
```PowerShell
        $ip = [IPAddress]::Any
        if (![IpAddress]::TryParse($Address,[ref]$ip)) {
            $ip = Get-CimInstance -ComputerName $Address -Class Win32_NetworkAdapterConfiguration -ErrorAction SilentlyContinue | Where-Object DefaultIPGateway | Select-Object -exp IPaddress | Select-Object -first 1
            #If we don't get an IP address for the computer, then fail
            If (!($ip)){
                Write-Error "Failed to obtain IP address for $Address. The error returned was:`r`n$Error[0]"
            }
            $Address = $ip      
        }
```
then I use (Get-Pool ...).memberReference.link to get the members which are filtered client side.  For now.  I'm still experimenting when time allows.

I haven't started Add-PoolMember, but would reuse Address the same as above and allow a separate, optional Name override.  If not specificed, the default name would be ipaddress:port.

**Comment by vercellone** [comment]
Commit 57ad8c7 fixed this issue.
