### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by aedahl** [joel74/POSH-LTM-Rest#186]
Would you consider adding a license to your project? 

Without express permission, submitting contributions to an un-licensed project project is something with which I am uncomfortable.

**Comment by joel74** [comment]
I'd consider adding the MIT license to the project. Is that sufficient for your purposes?

**Comment by aedahl** [comment]
In the past, I have found it useful for my own projects. Is it suitable for you and *your* purposes is the better question.

**Comment by joel74** [comment]
I currently don't have strong feelings either for or against. I'll add the MIT license in a bit.

**Comment by joel74** [comment]
License created
