### ISSUE TITLE
set-irule failing with unknown property error

### ISSUE THREAD

**Issue by Tedford** [joel74/POSH-LTM-Rest#188]
I just started using the powershell module so good chance that I am doing something wrong but all of my attempts to create an iRule failed.  I captured the network calls made when calling `Set-iRule` and the first fails with a 401, X-F5-Auth-Token does not exist, and and the second with a 400, unknown property.  However, all of `get-*` cmdlets are working with the same session object.  Below is an example where I attempting to roundtrip an existing rule.

**F5 version**: BIG-IP 13.1.0.2 Build 0.0.6 Point Release 2
**F5-LTM Version**: 1.4.281

```Powershell
$session = New-F5Session -LTMName $ip -LTMCredentials $cred -PassThru -TokenLifespan 1440
$rule = Get-iRule -F5Session $session -Name HTTP_iRULE_Test -Verbose
Set-iRule -F5Session $session -name $rule.name -iRuleContent $rule.Definition
```

**Error 1**

> {"code":401,"message":"X-F5-Auth-Token does not exist.","referer":"<ip>","restOperationId":16593227,"errorStack":["java.lang.SecurityException: X-F5-Auth-Token does not exist.","at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:249)","at com.f5.rest.workers.EvaluatePermissions.access$100(EvaluatePermissions.java:24)","at com.f5.rest.workers.EvaluatePermissions$1.failed(EvaluatePermissions.java:93)","at com.f5.rest.workers.EvaluatePermissions$1.failed(EvaluatePermissions.java:84)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2494)","at com.f5.rest.common.RestWorker$3.failed(RestWorker.java:751)","at com.f5.rest.common.RestWorker$3.failed(RestWorker.java:724)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2494)","at com.f5.rest.common.RestCollectionItemsLoadedCompletion.failRequest(RestCollectionItemsLoadedCompletion.java:86)","at com.f5.rest.common.RestCollectionItemsLoadedCompletion.failed(RestCollectionItemsLoadedCompletion.java:76)","at com.f5.rest.common.RestCollectionItemsLoadedCompletion.failed(RestCollectionItemsLoadedCompletion.java:22)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2494)","at com.f5.rest.common.RestWorker$3.failed(RestWorker.java:751)","at com.f5.rest.common.RestWorker$3.failed(RestWorker.java:724)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2494)","at com.f5.rest.workers.storage.StorageWorker.onQuery(StorageWorker.java:256)","at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1152)","at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1119)","at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1385)","at com.f5.rest.common.RestServer.access$000(RestServer.java:48)","at com.f5.rest.common.RestServer$1.run(RestServer.java:329)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:745)\n"],"kind":":resterrorresponse"}

**Error 2**

> {"code":400,"message":"\"{\" unknown property","errorStack":[],"apiError":26214401}

**Comment by joel74** [comment]
HI, if all Get- calls are working and Set- calls are failing, then it sounds like the user you're using to authenticate to the API doesn't have change permissions, only read. Are you able to make other changes to the LTM?

**Comment by Tedford** [comment]
The account I am using is an Administrator on All Partitions.  After I filed this issue I continued the process of trying out the other cmdlets and `Test-Functionality` cmdlet runs successfully.   Returning to my initial case of trying to create an iRule I was able to create an extremely basic iRule with the content **of #hello World**.  However, it seems that as soon as I add to define anything other than a 1-line comment the `set-iRule` cmdlet fails.  Furthermore, in the case of the 1 line comment that iRule is created but has an empty definition in the F5 portal.

**Comment by joel74** [comment]
Hi, I was able to create a sample multi-line iRule using the content of an existing iRule:
https://gist.github.com/joel74/7d38a0d7e59e1ff470ff74a9436393db
And I validated that the expected content was in the iRule

**Comment by Tedford** [comment]
Joel,

Thank you very much for your help.  Your example was instrumental in enabling me to get a rule successfully uploaded.  Ultimately it seems the issue was with one of the commands I was attempting to set.  A minimalistic representation is as follows.  For some reason the test to determine if the variable was defined would not upload.  The syntax works if entered directly into the F5 portal and happened to be the rule I was trying to roundtrip in my initial testing.

**This would cause set-irule to fail**
```tcl
when HTTP_REQUEST {
  set cert [SSL::cert 0]
   if { $cert != "" }
  {
      HTTP::header replace "x-client-cert"  [b64encode $cert]
  }
}
```

**This was the workaround**
```tcl
when HTTP_REQUEST {
   if { [SSL::cert 0] != "" }
  {
      HTTP::header replace "x-client-cert"  [b64encode [SSL::cert 0]]
  }

**Comment by joel74** [comment]
I'm glad you were able to get this working and that my example was useful. And thanks for using the module!
