### ISSUE TITLE
New-F5Session does not return a Session

### ISSUE THREAD

**Issue by pwahlmueller** [joel74/POSH-LTM-Rest#191]
It took me some time to understand, that sometimes the Session is needed as parameter (like Test-F5Session) and sometimes it is the default parameter.
I have two suggestions on this:
1. Add an example to the warning like New-F5Session -passthrough
2. Add the existing session as default everywhere needed

**Comment by joel74** [comment]
Hi, is this issue still relevant with the warning you added to Test-F5Session? Thanks.

**Comment by pwahlmueller** [comment]
As I tried the module, I was somewhat confused, that one function has the session as default and the other needs the session as parameter. The last session should always be as default in my opinion. What do you think?
(point 1 I fixed for me)

**Comment by joel74** [comment]
Closing with merge of #195
