### ISSUE TITLE
Remove Function ask for User Input to confirm the action

### ISSUE THREAD

**Issue by KlausBilger** [joel74/POSH-LTM-Rest#193]
the remove function is always asking to "perform the Action". 
Remove-PoolMember -F5Session $session -PoolName "" -Partition ""  -Name ""

Are you sure you want to perform this action?
Performing the operation "Remove-PoolMember" on target .
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "Yes"): Y

is there any way to use a Switch to override the question, otherwise this will not work in "silent mode" 

klaus

**Comment by pwahlmueller** [comment]
You can surppress this with the parameter -Confirm:$false

so this should work:
Remove-PoolMember -F5Session $session -PoolName "" -Partition "" -Name "" -confirm:$false

**Comment by joel74** [comment]
Correct. This and other functions with ConfirmImpact="High"should prompt for confirmation unless "-confirm:$false" is explicitly passed in.

**Comment by KlausBilger** [comment]
Joel 74, many thanks for the detailed information.
The functions are very helpful and save a lot of time - excellent work!

Thanks also to Patrick He is sitting in the office next to me.
