### ISSUE TITLE
Certification handling

### ISSUE THREAD

**Issue by pwahlmueller** [joel74/POSH-LTM-Rest#194]
Have I overlooked something or is the handling of certificates still missing?

**Comment by joel74** [comment]
There are currently no functions for importing or creating SSL certs.

**Comment by kleinsmk** [comment]
@pwahlmueller Check out my F5-deploy deploy module and look at Generate-CSR, Get-CSR, and Upload-Cert.  I extended the work Joel did for my own needs, but never bothered to refactor to try to get a pull request in.  Just make sure you have an $F5session session variable.  You can look at the structure of the other cmdlets and see how you can quickly roll your on New-Something and Get-Something commandlets if you know the API resource.

**Comment by joel74** [comment]
Closing - inactive.
