### ISSUE TITLE
get-virtualserver -name function fails if virtual is part of an iApp

### ISSUE THREAD

**Issue by Th3Stranger** [joel74/POSH-LTM-Rest#201]
Running cmdlet get-virutalserver -name <name of the virtual server> on a virtual server that's part of an iapp fails.  Appears to use the full path and misses the application in the path.

**Comment by SCMoperations** [comment]
Hmm.. This line in the function should be including the app info if it gets passed in:

`
               if(![string]::IsNullOrWhiteSpace($Application)) {
                    $items = $items | Where-Object {$_.fullPath -eq "/$($_.partition)/$Application.app/$($_.name)"}
                }
`
I'll need to run some tests to confirm. What version of the LTM are you using?

**Comment by Th3Stranger** [comment]
Thank you, appreciate the response.
I see now, if the VS is part of an iApp get-virtualserver -name <vserver> -app <iapp>.    Is there a forum for more info on using the functions?

**Comment by SCMoperations** [comment]
Great, I'll mark this as resolved. I think what would be helpful is for me to include an example in the Get-VirtualServer PS function that demonstrates how to call with an IApp. I'm open to suggestions on other ways to provide info about the functions, though I can't promise I'll be able to devote much time to working on any sizable project.

**Comment by joel74** [comment]
As designed. Resolved.
