### ISSUE TITLE
Issue with Connecting to F5 REST Error.

### ISSUE THREAD

**Issue by g-pearl** [joel74/POSH-LTM-Rest#202]
I am creating a configuration report and I am trying to get the ASM schedule

This code works on 10+ other F5's but fails on 2.

```
$ASM_Update_uri = "https://$F5_Device/mgmt/tm/asm/signature-update"
$ASM_Update_Response = Invoke-RestMethodOverride -Method Get -Uri $ASM_Update_uri -Credential $API_Cred
```

Error is 
```
Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
At C:\Program Files\WindowsPowerShell\Modules\f5-ltm\1.4.295\Public\Invoke-RestMethodOverride.ps1:26 char:9
+         Invoke-RestMethod @PSBoundParameters
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

I have tried to set the 
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 `
But still no goes. 

Any Ideas on the issue?
I am sure that it is a setting on these appliance but I am not sure what it could be.

**Comment by SCMoperations** [comment]
Are all the F5s using the same type of certificate? Like you said, there's got to be some difference in how security is configured on the appliances. Are you sure that all of them support TLS 1.2?

**Comment by g-pearl** [comment]
All Appliance have the same firmware installed.  I am unaware how to change the TLS version on the Management page - I understand on a VIP.  Do you have an article that explains how to verifiy for the MGT page?

These two appliance are managed by another person (hence the reason I am trying to create a config report).

Thanks for the help

**Comment by joel74** [comment]
Hi, did you try posting your question on F5's devcentral site? This issue seems to be broader and not specific to this F5 PowerShell module. Thanks.

**Comment by joel74** [comment]
Closing. I don't think the error referenced is specific to this module.
