### ISSUE TITLE
Resolve-NestedStats.ps1 needs continual modification

### ISSUE THREAD

**Issue by ScotteJH** [joel74/POSH-LTM-Rest#203]
Currently, the switch block needs to be updated for each major version that's released. This recently bit me when we moved to version 15 and suddenly Get-NodeStats quit working. I suggest changing the default to assume conversion is needed since that seems to be the future direction.

        Default { $JSON = $JSON.entries.PSObject.Properties.Value.nestedStats; }

Alternatively, reworking the switch block to use ranges of versions

    switch ($F5Session.LTMVersion.Major)
    {
        {$_ -gt 11} { $JSON = $JSON.entries.PSObject.Properties.Value.nestedStats; }
        Default { <# assume no conversion needed #> }
    }

**Comment by joel74** [comment]
Makes sense to me, Scott. Want to make a pull request with your suggested change? Thanks, Joel
