### ISSUE TITLE
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null

### ISSUE THREAD

**Issue by guptatarun1989** [joel74/POSH-LTM-Rest#205]
Hi @joel74 /Team ,
   I am able  to  run the same code to connect to multiple F5 LTM  and pull out the data but for Few F5 LTM  i am getting this error :

![image](https://user-images.githubusercontent.com/62771038/86467744-94868300-bd53-11ea-9157-1b0c821b476e.png)

Below is my code 
$LTM=@("10.231.238.69","10.231.238.129")
foreach ($eachLTM in $LTM)
{
try{
$f5session=New-F5session -ltmname $eachLTM -PassThru -LTMCredentials $LTMCredentials -ErrorAction Continue
}
catch
{
write-host "Could not conenct to F5 LTM $($eachLTM)" -ForegroundColor Green
$badLTM +=$eachLTM
Continue
}
}
Write-host "Current F5 connection" -ForegroundColor Green
$f5session

$poollist=@(Get-Pool -F5Session $f5session)

I was going through another thread which indicated  authorization issue but i am able to login via same admin password in GUI .  

Please help me on this .

**Comment by guptatarun1989** [comment]
I have also tried 
$poollist=**Get-Pool -F5Session $f5session | Select-Object -ExpandProperty fullPath ConvertFrom-Json**   but same result ...

**Comment by guptatarun1989** [comment]
![image](https://user-images.githubusercontent.com/62771038/86537718-df002f00-bf0e-11ea-8f9a-1eb6872f1110.png)

Here is another error  for another F5. I am able to run for 80 F5 but getting this error for 10 F5 where i am able to login in GUI.

Please tell me what i am doing wrong ?

**Comment by joel74** [comment]
Hi. Are you an admin / are you using an admin account on all the F5s to which you're attempting to connect?

**Comment by guptatarun1989** [comment]
Hi @joel74 ,
  Yes  , i am using admin account to login into F5.  
username " admin"
password "XXXX"

I am able to login in GUI via same password . ( All the F5 in our infra have same admin password  ) .

![image](https://user-images.githubusercontent.com/62771038/86571892-cf74fa80-bf8f-11ea-9c48-c30157c53b20.png).

For example : F5 LTM  10.231.238.69  . Initially i thought this F5 might be empty  or some invalid configuration  which may be throwing eroor  ,  This F5 has live   66 Virtual servers, 72 pool member's etc..

I have attached my Powershell code just in case you want to have a look . 
[F5-poolmembers-v2-WORKING.zip](https://github.com/joel74/POSH-LTM-Rest/files/4877635/F5-poolmembers-v2-WORKING.zip)

**Comment by guptatarun1989** [comment]
HI team ,
    if anyone can help me on this , please let me know ..  I am getting this error and i have no idea how to resolve the same . 
is there any workaround ?

**Comment by joel74** [comment]
Hi, guptatarun1989, if the situation is still the same as when you first posted, and this works on some of your F5s and not on others, then there must be a difference in configuration between them. I'm sorry, but I am super busy with many other things at the moment and can't help troubleshoot further. I recommend taking a very close look at the configs for your F5s, posting on DevCentral with your question and utilizing F5 support. 
Good luck.
