### ISSUE TITLE
can I get batches using Get-VirtualServer

### ISSUE THREAD

**Issue by bryancan** [joel74/POSH-LTM-Rest#206]
I have so many virtual servers in some of my F5 that timeouts are happening. 
Is there a way I can fetch virtual servers in smaller batches vs all at once?

**Comment by joel74** [comment]
Hi, the name parameter does accept an array of strings, so if you pass in an array, like 
Get-VirtualServer -Name @('virtualserver1','virtualserver2')
you can retrieve a specific set of virtual servers that way. Unfortunately there is no wildcard support currently.
