### ISSUE TITLE
New-F5Session Breaks on version 15.1.4

### ISSUE THREAD

**Issue by purduerich** [joel74/POSH-LTM-Rest#213]
Hey team.  I've been using this Powershell module for years and it's been working great.  Recently I applied the v15.1.4 patch to one of our non-prod load balancers.  The following morning our automated tests which utilize this module started getting the error below.

```
Invoke-F5RestMethod : "401 F5 Authorization Required: Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/tm/sys/version/ Referrer:xxx.xxx.xxx.xxx Sender:xxx.xxx.xxx.xxx
At C:\Program Files\WindowsPowerShell\Modules\F5-LTM\1.4.308\Public\New-F5Session.ps1:98 char:13
+     $JSON = Invoke-F5RestMethod -Method Get -Uri $VersionURL -F5Sessi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-F5RestMethod
```

I double checked my service account and access and all of that was working fine in the admin UI.  However it seems like this call started failing.  If you look at my screenshot below you'll see 2 calls being made.  The top one is connecting to a load balancer on v15.1.3.1, which is successful.  The second one is connecting to a load balancer on v15.1.4 which is unsuccessful.

![image](https://user-images.githubusercontent.com/13188762/136814385-b07f915a-56a3-4a75-8645-269db8184aa9.png)

I wonder if F5 introduced changes in iControl that changed its behavior.  I'm reporting this as a possible bug.

**Comment by joel74** [comment]
Thanks for providing the details, purduerich.
