### ISSUE TITLE
iterating through multiple f5's

### ISSUE THREAD

**Issue by kimalat** [joel74/POSH-LTM-Rest#216]
I am trying to use your script to iterate through multiple F5's , the first one works on the  2nd one i get a 401.
my process has been :
create a new session 
run the commands
remove the session 
connect to other ff5
run a command ( this is where i get the 401.)

Running these manually works, when running them in a ps1 i have 401 errors. Any ideas?

**Comment by joel74** [comment]
Hi. Have you tried using the PassThru switch, and storing and examining the 2nd session, to ensure it's formatted as expected? If you use PassThru, then you can manage multiple sessions simultaneously, as long as you're included them when calling the functions.

**Comment by joel74** [comment]
Closing as stale.
