### ISSUE TITLE
Unable to run New-F5Session in PS < 6.0

### ISSUE THREAD

**Issue by boz987** [joel74/POSH-LTM-Rest#217]
Unable to find type [System.Management.Automation.SemanticVersion].
At C:\Program Files\WindowsPowerShell\Modules\F5-LTM\1.4.313\Public\New-F5Session.ps1:22 char:40

https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.ivalidatesetvaluesgenerator?view=pscore-6.0.0

Server 2022 still comes with Powershell 5.1 as default.

**Comment by joel74** [comment]
Thanks. I will take a look. Since I still claim the module supports PowerShell v3+, I shouldn't be using a class that's only is 6 and up.

**Comment by joel74** [comment]
Fixed with this commit. Thanks for catching this.
https://github.com/joel74/POSH-LTM-Rest/commit/98303b1538d6e813e12f130b87cdd7eaf31fb8a0
