### ISSUE TITLE
2 active New-F5Sessions in the same PS Script?

### ISSUE THREAD

**Issue by llyons** [joel74/POSH-LTM-Rest#219]
Hi,   We have some automation around some F5 functionality.  We have moved from 1 F5 to 2 F5s,  one for external apps and one for internal apps.   In our powershell automation we now have to create two different F5 sessions depending on which F5 we want to make changes in.  I have a snippet of the PS code below.

Is there any way to close the session that was opened and then create a new session?

We are finding the creating a New-F5session when one has already been created doesnt work and still uses the first session opened. 

Current PS snippet
```
$ltmip = "1.2.3.4"      
$ltmip_inside = "1.3.3.4"            

         if ($vipName.ToLower() -contains "internal") {
             $session = New-F5Session -LTMName $ltmip_inside -LTMCredentials $mycreds
         } else {
             $session = New-F5Session -LTMName $ltmip -LTMCredentials $mycreds          
          }
.
.
.

      $add = Add-iRuleToVirtualServer -InputObject $vipObject -iRuleName $all_MaintRule
``` 

Can I have 2 sessions in same script space and use the  Add-iRuleToVirtualServer   with some sessionID?

```
      $session_inside = New-F5Session -LTMName $ltmip_inside -LTMCredentials $mycreds
      $session_ext = New-F5Session -LTMName $ltmip -LTMCredentials $mycreds      

      $add = Add-iRuleToVirtualServer -InputObject $vipObject -iRuleName $all_MaintRule -session session_inside

      $add = Add-iRuleToVirtualServer -InputObject $vipObject -iRuleName $all_MaintRule -session session_ext

```

**Comment by joel74** [comment]
Hi. You need to utilize the -PassThru flag with the New-F5Session calls to get back the different sessions. Otherwise it will just pick up the default.
