### ISSUE TITLE
Terminating error when using set-strictmode

### ISSUE THREAD

**Issue by Ben-Conrad** [joel74/POSH-LTM-Rest#222]
We use set-strictmode -version 2 in all of our scripts, for coding sanity and best practices.  I noticed in the output of Get-VirtualServer that if the VirtualServer on the LTM does not have a pool assigned to it the return from the CMDLET will not have the 'Pool' property.  Get-Member shows the property does not exist if it's empty. 
 This breaks where-object and even calling when the property:

```$virtual = Get-VirtualServer

# I picked an element that does not have a pool member:
PS C:\> $virtual[-2].pool
The property 'pool' cannot be found on this object. Verify that the property exists.
At line:1 char:1
+ $virtual[-2].pool

# Same issue with where-object:
PS C:\> $virtual | ? { $_.Pool -like "*Anything*" }
? : The property 'Pool' cannot be found on this object. Verify that the property exists.
At line:1 char:12
+ $virtual | ? { $_.Pool -like "*Anything*" }
```

Things work fine when strictmode is not enforced.   

I see the property is missing because of the F5 REST API, it's missing from this response:
$JSON = Invoke-F5RestMethod -Method Get -Uri $URI -F5Session $F5Session

$JSONHasPool.PSobject.Properties['Pool']
MemberType      : NoteProperty
IsSettable      : True
IsGettable      : True
Value           : my pool name
TypeNameOfValue : System.String
Name            : pool
IsInstance      : True

$JSONNoPool.PSobject.Properties['Pool']
PS >

I figure that the above test could be added after line 52 in Get-VirtualServer.ps1 but I imagine there could be a lot of other scripts that have the same behavior.

Any thoughts on how to proceed?  I guess one option is to disable strict mode but we really try not to do that.

Thanks,

Ben

**Comment by joel74** [comment]
Hi, Ben.
There is a private function in the module called Add-ObjectDetail that is called at the end of Get-VirtualServer. In my understanding, it is meant to ensure that the virtual server object returned does have all the expected properties. Another individual contributed that code to the module so I'm not super familiar with it. I will try to dig into it a bit though and see why it's not operating as expected.
- Joel

**Comment by joel74** [comment]
Hi, Ben,
Sorry for the delay. I haven't had the cycles to dig into this again until recently. From what I can tell so far, Add-ObjectDetail is supposed to apply formatting for the custom LTM types like virtual servers, but the module does not (yet) have a custom types file, only a custom format file. I'm going to test with creating a custom types file and see if applying that custom types correctly results in adherence to strict object format.

**Comment by joel74** [comment]
Hi, Ben,
The new branch I just created (fix-strict-mode) fixes this issue for virtual servers only. I just tested it successfully with strict mode v2. I'll start working on adding the other types. If you have a moment, maybe you can grab the code for that branch and confirm that it works for you. 
Thanks, Joel

**Comment by joel74** [comment]
This branch has been merged.
