### ISSUE TITLE
get-irule definition alias

### ISSUE THREAD

**Issue by Curtmcgirt** [joel74/POSH-LTM-Rest#226]
having an issue on some machines where get-irule errors with:

Add-Member : Cannot add a member with the name "Definition" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.

the $response does still include apiAnonymous as populated. so $response shows the definition, but $response.definition is blank. $response.apiAnonymous shows the irule. 

the same command on the same irule works fine from other machines.  i've tried it on two 2016 servers and two win10 workstations, and it only works on one of the win10 workstations. (guessing the function is populating an arraylist, and this is more to do with powershell than with this specific module)

**Comment by joel74** [comment]
Hi, @Curtmcgirt. It sounds like you're on to something. 
When you have a moment, can you check the versions of PowerShell (PS> $psversiontable.psversion) and see which one(s) work and which don't? That might shed some more light.

**Comment by Curtmcgirt** [comment]
the two windows 10 machines are both  5.1.19041.1682, and only one of them works. :/

**Comment by joel74** [comment]
That's bizarre. I guess the next thing to verify is whether you're using the same version of the module on all the servers:
get-module f5-ltm

**Comment by cmuesing** [comment]
I am running into this issue also. We are running on a Windows Server 2019 on Powershell 5.1.17763.3770. How would I get around this error?

**Comment by cmuesing** [comment]
I only have two 2019 servers to try it with, but both are running the same version of PS, 5.1.17763.3770 and it fails on both. I am using the same version of F5-LTM, pulling it from PowershellGallery.com. Version 1.4.319.

**Comment by cmuesing** [comment]
joel74, we are trying to add additional logging and wonder if the iRule format must be in a valid json format. The module Get-iRule.ps1 has this if statement on line 33, where our iRule comes back with the .name, but there are no object items to send through the next command for Invoke-NullCoalescing. We get the same result on all the iRules we have tried in our F5. 
![2023-05-22_16-49-43](https://github.com/joel74/POSH-LTM-Rest/assets/51469723/ca1f9e82-c54b-4623-88bd-daabdecece9c)

**Comment by cmuesing** [comment]
Thanks @joel74. If I understood the data in the background of the F5 iRule, I might be able to figure it out. But we do not have permissions here to see it and I truly appreciate your assistance. We will be watching this thread for your findings.

**Comment by joel74** [comment]
Hi, @cmuesing , you can use this gist to update the script in Get-iRule.ps1 in your local instance. If you set $Debugreference to 'Continue' you'll see what's being returned when you get the iRule.
https://gist.github.com/joel74/bfc4beb79d4030b52552cced52535e0a

**Comment by joel74** [comment]
Hi, @cmuesing , did you get a chance to test with the gist I sent? Thanks.

**Comment by joel74** [comment]
Closing this issue since the recent PR fixed the warning message.
