### ISSUE TITLE
Should the F5 session be stored in global/local scope?

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#23]
I've received a number of questions from people who don't understand that the F5 session object needs to be stored in a variable and passed to the functions. This got me wondering if it would be better to use the Get-F5Session function to create a credential object with local or global scope and allow the other functions to reference this without having to pass this in. 

On one hand, this feels like bad form because it makes the functions dependent on something external that's not passed to them. On the other hand, it seems like it would help simplify things. 

Thoughts?

**Comment by vercellone** [comment]
Yes.  Absolutely.  F5Session should be stored in module scope.

You can see that I added $F5LTMSession=$null on line 14 of the psm1.  My local working copy of Get-F5Session sets $Script:F5LTMSession which I use as a default elsewhere.  It is a temporary hack for my own convenience,

For a permanent solution, I like what @RamblingCookieMonster has done in his [Infoblox](https://github.com/RamblingCookieMonster/Infoblox) module.

**Comment by joel74** [comment]
Ok, good feedback. I've started messing around with this. I'm thinking there will be a new function (New-F5Session) that will take the LTM name/IP and credentials, as well as a Scope value (either Local or Script). If Local, the session object is returned. If Script, it's stored in the Script scope. Eventually, Get-F5Session will be deprecated.

I'd like to use $Script:F5Session as the default F5 session object for each function that needs one, but I don't believe there's a neat way to make the F5Session param be mandatory but also make $Script:F5Session the default value, so I may just need to remove the mandatory param setting and test for a session object. I'll work on incorporating the token authentication into the New-F5Session function as well.

**Comment by vercellone** [comment]
What do you think about having New-F5Session unconditionally add/update an item to a $Script scoped collection (Dictionary) using a Name key which defaults to the LTMName?  To support the Local use case, include a -PassThrough switch.  The first session created should unconditionally be made the default.  A -Default switch could determine whether subsequently added sessions overwrite the default.

Yes, you'll need to make F5Session Mandatory=$false.

**Comment by joel74** [comment]
I think we're headed in the right direction. My current iteration takes LTMName, LTMCredentials, and the optional switches -Default and -PassThrough as params. If -Default is set and/or if $Script:F5Session doesn't exist, then $Script:F5Session is created. If -PassThrough is set, then the dictionary is returned to the caller.

There is the one possible scenario where $Script:F5Session already exists, and neither the -Default nor the -PassThrough switch are set in the function call, so the call basically does nothing. Other than that, I think all bases are covered.

**Comment by joel74** [comment]
Changed committed. There may be further refinements to this new method for creating and managing the script-scoped F5 session, but I believe sufficient work has been done to close this issue.

**Comment by vercellone** [comment]
Please add New-F5Session and Test-F5Session.  They weren't included in d16bb11.

**Comment by joel74** [comment]
Added. I thought SourceTree would pick up new files added to the Public folder, but for some reason they didn't show up initially.
