### ISSUE TITLE
Add-PoolMember with an existing node fails

### ISSUE THREAD

**Issue by vercellone** [joel74/POSH-LTM-Rest#28]
Exact error and solution: [Add a new pool with an existing node](https://devcentral.f5.com/questions/add-a-new-pool-with-an-existing-node)

**Comment by joel74** [comment]
Is the problem with Add-PoolMember or with New-Pool? 
I was able to add a computer that was already a node in another pool to a new pool.
What are the exact steps to repro this?
Thanks.

**Comment by vercellone** [comment]
Add-PoolMember

:x: 400 Bad Request: 0107003:3: Pool member node (/[Partition]/[IPAddress]) and existing node (/[Partition]/[ComputerName]) cannot use the same IP address ([IPAddress])

I have come to realize that this only happens when the pool member name doesn't match the node name.  Unfortunately, this is typical in my scenario where the node name is [ComputerName]:[PortNumber] rather than Add-PoolMember's default of [IPAddress]:[PortNumber].  If -Name is specified as [ComputerName]:[PortNumber] when calling Add-PoolMember it works fine.

Options:
- Use Get-Node, and if the node exists use the existing node's name as the basis for the new member.
- Do nothing.  The error is inconvenient, but possibly descriptive enough as-is.

That said, the automatic IP address resolution has been nagging me.  Perhaps a separate issue.  It should probably at least be refactored into it's own method so it could potentially be overridden if necessary.  The current solution doesn't resolve the IP address correctly (for me) over a VPN connection even though I can ping the server by name.

**Comment by elijahgagne** [comment]
For what it's worth, the way automatic IP address resolution is implemented does not work for my environment either. A majority of my servers Linux, so running `Get-CimInstance -ComputerName $Address -Class Win32_NetworkAdapterConfiguration` just fails.

I've taken part of this repository as a starting point and written new functions to aid a F5 migration we're doing. A lot of my functions revolve around creating iApps from templates and comparing configurations. In my functions, I've implemented IP to hostname resolution by doing a call such as `([System.Net.Dns]::gethostentry($ip)).hostname`.

I really like the idea of refactoring this duty to it's own function so that it could be overridden. Most of my code is rough and specific to the tasks I am doing, but I would be interested making it more generic and attempting to contribute parts that make sense to this project.

**Comment by joel74** [comment]
I realize that the New-Pool and Add-PoolMember scripts will need updating to resolve this issue, and to not rely on a member name being an IP address. For now, I've removed the calls to Get-CimInstance in Add-PoolMember.ps1, Get-PoolMember.ps1, and New-Pool.ps1, and used the GetHostAddresses method in the [System.Net.Dns] class. 

However, I find it very confusing to alias the Address field with 'ComputerName.' What I may end up doing is cleaning up references to ComputerName, but the issue I have is that everything in my environment of 1000+ servers expects to be able to pass a computer name to a function in the module, while all pool members are represented as IP addresses, hence the computername-to-IP address conversion. A custom help function may be what I need, but that could be a good bit of work on my end.

**Comment by vercellone** [comment]
I included the ComputerName alias for $Address primarily to avoid a breaking change.  Ideally, I think the Address parameter should be strongly typed as [System.Net.IPAddress], with no automatic resolution baked in.

But, I feel your pain regarding cleaning up existing code.

As a compromise: Address and ComputerName could be implemented as mutually exclusive ParameterSetName(s) with ip resolution occurring only when $PSCmdlet.ParameterSetName -eq 'ComputerName'.

**Comment by joel74** [comment]
I've start down this path, but found it treacherous, at least for my coding ability. I like the idea of having param sets for: IP address, computer name, pool member name and input object. However, I found that I needed an additional param set called 'ShowAll' to allow for not passing in a member and displaying all members in a pool or pools. 

I'm not a big fan of the function having to call itself simply to retrieve the MemberLink. I currently have an implementation that retrieves all MemberLink values in the {Begin} section and then processes them based on the appropriate param set. I'm beginning to wonder, though, if we're trying to accommodate too much. Why accept both names/strings and objects? It might be better to standardize and functions take one or the other? I'm not sure. Thoughts? Thanks.

**Comment by elijahgagne** [comment]
What do you think of having a New-PoolMember commandlet that handles all of the logic necessary to construct a pool member object? Add-PoolMember would then take the PoolMember object as input and add it to an existing pool.

**Comment by joel74** [comment]
I like that idea, but we still have the issue of deciding what params / param sets Get-PoolMember and Remove-PoolMember would take. My thought is to have Get-PoolMember and New-PoolMember both accept either an IP, a member name or a computer name, and return a pool member object. That object could then be piped to Add-PoolMember or Remove-PoolMember. However, Get-PoolMember and New-PoolMember wouldn't need to handle being passed an object.

**Comment by vercellone** [comment]
This may not look pretty, but gets the job done:
```PowerShell
Function Add-PoolMember {
    [cmdletBinding()]
    param (
        $F5Session=$Script:F5Session,

        [Parameter(Mandatory=$true,ParameterSetName='InputObjectWithAddress',ValueFromPipeline=$true)]
        [Parameter(Mandatory=$true,ParameterSetName='InputObjectWithComputerName',ValueFromPipeline=$true)]
        [Alias("Pool")]
        [PSObject[]]$InputObject,

        [Parameter(Mandatory=$true,ParameterSetName='PoolNameWithAddress',ValueFromPipeline=$true)]
        [Parameter(Mandatory=$true,ParameterSetName='PoolNameWithComputerName')]
        [string[]]$PoolName,
        [Parameter(Mandatory=$false,ParameterSetName='PoolNameWithAddress',ValueFromPipeline=$true)]
        [Parameter(Mandatory=$false,ParameterSetName='PoolNameWithComputerName')]
        [string]$Partition,

        [Parameter(Mandatory=$false,ParameterSetName='InputObjectWithAddress')]
        [Parameter(Mandatory=$false,ParameterSetName='PoolNameWithAddress')]
        [Parameter(Mandatory=$true,ParameterSetName='InputObjectWithComputerName')]
        [Parameter(Mandatory=$true,ParameterSetName='PoolNameWithComputerName')]
        [string]$ComputerName,
        [Parameter(Mandatory=$true,ParameterSetName='InputObjectWithAddress')]
        [Parameter(Mandatory=$true,ParameterSetName='PoolNameWithAddress')]
        [Parameter(Mandatory=$false,ParameterSetName='InputObjectWithComputerName')]
        [Parameter(Mandatory=$false,ParameterSetName='PoolNameWithComputerName')]
        [IPAddress]$Address,

        [Parameter(Mandatory=$false)]
        [string]$Name,
        
        [Parameter(Mandatory=$true)]
        [ValidateRange(0,65535)]
        [int]$PortNumber,

        [ValidateSet("Enabled","Disabled")]
        [Parameter(Mandatory=$true)]$Status
    )
    begin {
        if ($PSCmdLet.ParameterSetName -match 'ComputerName$') {
            $Address = [Net.Dns]::GetHostAddresses($ComputerName) | Where-Object { $_.AddressFamily -eq 'InterNetwork' }  | Select-Object -First 1
        }
    }
    process {
        $Address.IPAddressToString
        $PSCmdLet.ParameterSetName
        # The rest of the code wouldn't need to change much...
    }
}
cls
$pool = [pscustomobject]@{foo='bar';dummy='object'}
Add-PoolMember -InputObject $pool -computername 'AFW01VERCELLJW8' -PortNumber 80 -Status Enabled
Add-PoolMember -InputObject $pool -Address '192.168.1.9' -PortNumber 80 -Status Enabled
Add-PoolMember -PoolName /MyPartition/MyPool -computername 'AFW01VERCELLJW8' -PortNumber 80 -Status Enabled
Add-PoolMember -PoolName /MyPartition/MyPool -Address '192.168.1.9' -PortNumber 80 -Status Enabled
```

**Comment by joel74** [comment]
Thanks. I tweaked this a little (wildcards on the param set switches, a couple other small things) and got it to work consistently for me.
Committing those changes now. I'm planning to review Get-PoolMember and Remove-PoolMember as well, just to keep them consistent.

**Comment by vercellone** [comment]
Looks good.  Now that the parameters are working as desired, I've incorporated the fix for the issue originally reported into pull request #29.
