### ISSUE TITLE
Don't seem to be any ExportCommands

### ISSUE THREAD

**Issue by dsolodow** [joel74/POSH-LTM-Rest#3]
After adding the psm1 and psd1 files to the F5-LTM folder under Modules, I can do an 'import-module F5-LTM' without issue.

However, when I do 'get-command -module f5-ltm' the ExportedCommands property is empty and none of the modules are available. 

It looks like RootModule needs to be set in the manifest. When I made that change and re-ran the import-module everything behaved as expected.

**Comment by joel74** [comment]
Thanks, Damien. I'll make that change to the psd1 file.
