### ISSUE TITLE
Move ModuleVersion info from module to manifest

### ISSUE THREAD

**Issue by dsolodow** [joel74/POSH-LTM-Rest#4]
In the comment block of F5-LTM.psm1 I noticed a version line. 
The version listed there doesn't match what's in the manifest file, and the manifest is what controls the module version that -module commands seem to look at.

Does it make sense to remove the version line from the psm1 and just increment the ModuleVersion line in the manifest instead?

**Comment by joel74** [comment]
Yes. That version in the comment block is a hold-over from a pattern I used before I started using manifests. I'll pull that out.
