### ISSUE TITLE
CI Publish to PowerShell Gallery

### ISSUE THREAD

**Issue by vercellone** [joel74/POSH-LTM-Rest#42]
I suspect you realize that your AppVeyor build is not yet publishing to the PowerShell gallery.

You should test the Publish-Module command in your working directory to verify it works and publishes with the desired name.  Once you've perfected it, un-comment and edit the last line of your appveyor.yml accordingly.

**Comment by joel74** [comment]
Yes, thanks, I noticed that when I did the initial merge. I plan to test this soon.

**Comment by joel74** [comment]
Publishing successfully to PowerShell gallery.

**Comment by vercellone** [comment]
Install-Module works, but Import-Module fails for version 1.3.9.  It looks like I might have messed up the line endings due to a recent git tooling update on one of my computers.  Are you experiencing the same?

**Comment by vercellone** [comment]
Disregard.  Oddly, it is working now.

**Comment by joel74** [comment]
Strange. No clue why that happened.

**Comment by joel74** [comment]
Should I still accept the pull request?

**Comment by vercellone** [comment]
Yes.  It seems like a good idea to prevent line ending issues in the future.
