### ISSUE TITLE
Add support for iApps

### ISSUE THREAD

**Issue by elijahgagne** [joel74/POSH-LTM-Rest#45]
I don't see that the current code base supports iApps yet. For example:

```
Get-Pool -F5Session $F5Session -Name "sharepoint-2010-bmr-443_pool" -Partition "dev" -Verbose
VERBOSE: NB: Pool names are case-specific.
VERBOSE: GET https://ltm1.example.com/mgmt/tm/ltm/pool/~dev~sharepoint-2010-bmr-443_pool with
0-byte payload
Invoke-RestMethodOverride : "404 Not Found: 01020036:3: The requested Pool
(/dev/sharepoint-2010-bmr-443_pool) was not found.
```

The URL of the pool I am trying to query is at: https://ltm1.example.com/mgmt/tm/ltm/pool/~dev~sharepoint-2010-bmr-443.app~sharepoint-2010-bmr-443_pool

The URL format is $F5Session.BaseURL + '/pool/~$($Partition)~$($iApp).app~$($Pool)". It looks like Get-VirtualServer and other functions may have a similar problem.

I propose adding a new optional parameter to these functions that takes an iAppName. If this optional variable is present, it would be used to build the URL. Otherwise it would be ignored.

If this is something you would be open to, I'd be happy to try making the necessary updates and submitting a pull request. 

Thanks!
-EWG

**Comment by joel74** [comment]
Makes sense and seems like a good idea to me. So any function that takes a virtual server as a param would need to take an optional iApp value, correct?

**Comment by vercellone** [comment]
The current workaround is to specify the full name:
```PowerShell
Get-Pool -F5Session $F5Session -Name /dev/sharepoint-2010-bmr-443.app/sharepoint-2010-bmr-443_pool
```
That is a lot easier if the argument completion is working correctly.  I'll troubleshoot that ASAP.  In the meantime, what does devcentral have to say about apps and subfolders?  Is there a max depth for the fullPath of an F5 Item?

**Comment by joel74** [comment]
It appears there is a limit of 255 characters for folder paths of pools and virtual servers:
https://support.f5.com/kb/en-us/solutions/public/14000/400/sol14440.html

**Comment by vercellone** [comment]
- I submitted PR #48 to address the argument completion issue.
- I can't find any reason not to add an optional iApp parameter.  Please build the necessary logic into Private\Get-ItemPath.ps1.  And, we should plan on adding similar logic to Private\New-F5Item.ps1 and any relevant New-* functions in the near future.

**Comment by elijahgagne** [comment]
Great, I hope to have something in a few days.

**Comment by elijahgagne** [comment]
Initial support added in pull #50 so I will close this issue. Issue #54 was opened to improve support when Name is null.
