### ISSUE TITLE
PowerShell version requirement review

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#49]
The .psd1 still says that v3 is the minimum PS version requirement, but with the addition of Register-ArgumentCompletion, this was pushed to v5. Though my dev system is v5, my entire work environment is still v4, and I'm not feeling ready to make this module only available to people using v5. I'd prefer it to be v4.

I haven't done a full sweep, so I don't know if there are other cmdlets that require v5. Ideally we can implement smart version checking and only try to use v5-specific cmdlets if that's what the user has.

Thoughts?

**Comment by vercellone** [comment]
I'm spoiled.  Every machine I touch I install v5 on so I can use Install-Module from the PowerShell Gallery and my own internal Nuget repository.  I grew weary of using [PsGet](https://github.com/psget/psget).

But, I am happy to commit to v3 compatibility.  I've submitted PR 51, which addresses ArgumentCompletion compatibility.  Let me know if there are other outstanding issues.

**Comment by vercellone** [comment]
Mentioned this in PR #51, but want to note that: Argument completion should also work in v3+ if you install the [TabExpansionPlusPlus](https://github.com/lzybkr/TabExpansionPlusPlus) module.
