### ISSUE TITLE
Issues using Get-PoolMember(Stats)

### ISSUE THREAD

**Issue by elijahgagne** [joel74/POSH-LTM-Rest#55]
I have been reviewing Get-PoolMember(Stats) for two reasons. I would like to add the Application parameter to them and I plan to use them as a model to improve other Get-\* functions as described in issue #54. 

However, I am having a little trouble using and understanding Get-PoolMember(Stats). Let me start by showing example usage that works.

```
$testPartition1         = "dev"
$testPoolFullPath1      = "/dev/sharepoint-2010-bmr-443.app/sharepoint-2010-bmr-443_pool"
$testPoolMember1        = "10.0.0.1:80"
$testPoolMemberAddress1 = "10.0.0.1%4"

Get-PoolMember -PoolName $testPoolFullPath1 -Name $testPoolMember1 -Partition $testPartition1

Name             Partition Address         Description Monitor Session         State
----             --------- -------         ----------- ------- -------         -----
10.0.0.1:80      dev       10.0.0.1%4                  default monitor-enabled down 
```

Note that Address shows 10.0.0.1%4. Here's what I get when I pass Address to Get-PoolMember

```
Get-PoolMember -PoolName $testPoolFullPath1 -Address $testPoolMemberAddress1 -Partition $testPartition1
Exception calling "GetHostAddresses" with "1" argument(s): "No such host is known"
At C:\POSH-LTM-Rest\F5-LTM\Public\Get-PoolMember.ps1:42 char:21
+ ...             $Address = [string]([System.Net.Dns]::GetHostAddresses($A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SocketException

Exception calling "GetHostAddresses" with "1" argument(s): "No such host is known"
At C:\Users\d92495j\G\_Tasks\F5 PowerShell\POSH-LTM-Rest\F5-LTM\Public\Get-PoolMember.ps1:42 char:21
+ ...             $Address = [string]([System.Net.Dns]::GetHostAddresses($A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SocketException


Name             Partition Address         Description Monitor Session         State
----             --------- -------         ----------- ------- -------         -----
10.0.0.0:80      dev       10.0.0.0%4                  default monitor-enabled down
```

Looking at the code in Get-PoolMember.ps1, here is the relevant section:

```
36 if ($Address -ne '*') {
37     for ([int]$a=0; $a -lt $Address.Count; $a++) {
38         $ip = [IPAddress]::Any
39         if ([IpAddress]::TryParse($Address[$a],[ref]$ip)) {
40             $Address[$a] = $ip.IpAddressToString
41         } else {
42             $Address = [string]([System.Net.Dns]::GetHostAddresses($Address).IPAddressToString)
43             #If we don't get an IP address for the computer, try the value specified
44             If ($ip) {
45                 $Address[$a] = $ip
46             }
47         }
48     }
49 }
```

Line 42 is causing an uncaught exception, but then the rest of the function is working and successfully producing the desired output. 

I am trying to understand line 42. $Address is potentially an array that the for loop is processing. I do not think this line is properly handling the circumstance where $Address is an array of IPs. Nor is it gracefully handling when GetHostAddresses throws an exception. 

I am also not understanding lines 44-46. Line 38 initializes $ip so I don't see any circumstance where that if statement would evaluate false. So I'm thinking that it would be fine to remove lines 44 and 46, but keep 45. 

I'd be happy to propose some changes to this function, but if anyone has comments on why it was written like this, I'd very much like to hear them before I make changes that could break the original intentions.

**Comment by vercellone** [comment]
I think closed issues #18 and #28 are somewhat relevant.  The solution applied to Add-PoolMember for #28 should be applied to these other *-PoolMember* functions as well.

But, that alone won't solve the root problem you are reporting.  I don't think we realized (I know I didn't realize) that '10.0.0.1%4' was a valid pool member address.  It certainly can't be parsed by nor cast to a valid [System.Net.IPAddress].  Is that something new in v12?  What is the significance of '%4' in '10.0.0.1%4'.  It looks like a scope id, but I thought that was only applicable to ipv6 addresses for machines with multiple NICs.

**Comment by elijahgagne** [comment]
I am running with version 11.6. The percent %4 represents the dev partition. The Common partition is %1. I am thinking it is used to uniquely identify a node because we often have the same nodes in multiple partitions.

**Comment by elijahgagne** [comment]
A fix to my problem that keeps everything else working the same would be:

```
if ($Address -ne '*') {
    for ([int]$a=0; $a -lt $Address.Count; $a++) {
        $ip = [IPAddress]::Any
        if($Address[$a] -match "[\d\.]+%\d+") {
            # Do not alter $Address[$a] if in format of IP%Partition
        } elseif ([IpAddress]::TryParse($Address[$a],[ref]$ip)) {
            $Address[$a] = $ip.IpAddressToString
        } else {
            $Address = [string]([System.Net.Dns]::GetHostAddresses($Address).IPAddressToString)
            $Address[$a] = $ip
        }
    }
}
```

Do you think this is a good first step to take? If so, I'd like to propose making this change to Get-PoolMember(Stats).

**Comment by joel74** [comment]
Makes sense to me. I also didn't realize that pool member addresses might have a %{partition number}  added at the end.

**Comment by elijahgagne** [comment]
Great. I'll roll this change into what I'm working on for #54 since this change is so minor. It turns out Get-PoolMemberStats works fine for me, I just had a bad Pester test.

**Comment by vercellone** [comment]
Add-PoolMember won't work as-is.  You'll have to remove or replace the [IPAddress] type declaration to allow $Address input values that include '%'.

I suppose it is rhetorical, but may I ask why you append %{partition number} rather than just refer to the same node across partitions?  It seems like an unnecessary hack, which just increases your maintenance burden.  On my devices nodes in any partition can be added to pools in any other partition.

**Comment by elijahgagne** [comment]
What I've learned so far is that the ip%partition format seems to come up as soon as you have the node in the Common partition and another partition (e.g. dev). If the node is not in the Common partition, but it exists in two other partitions (e.g. dev and admin), the ip%partition format does not come into play. I'm thinking, but not sure on this, that the Common partition is a parent of all other partitions and it is needing to do this to uniquely identify the node. 

As to why I have the same node in the Common partition and other partitions, I'm not sure. I'm guessing this might have to do with the templates we use to create iApps. We have also been using the LTMs for about 10 years and there is a lot of legacy stuff that has carried over from previous hardware/versions. I'll keep researching this a bit.

**Comment by elijahgagne** [comment]
You are certainly right that Add-PoolMember gives me some issues. Here's some details on how things are working for me:
```
# These all work as expected
Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Partition dev
Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.0.0.1:443 -Partition dev
Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.0.0.1:443 -Address 10.0.0.1 -Partition dev
Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.0.0.1:443 -Address 10.0.0.1%4 -Partition dev

# This one only works with my proposed fix
Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.0.0.1%4 -Partition dev

# This one fails for me no matter what
Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.0.0.1 -Partition dev

# Here's what happens when I try to add a poolmember
Add-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.0.0.1%4 -PortNumber 443 -Status Enabled -Partition dev
Add-PoolMember : Cannot process argument transformation on parameter 'Address'. Cannot convert value "10.0.0.1%4" to type "System.Net.IPAddress". Error: "An invalid IP address was specified."
At line:1 char:70
+ ... sion $F5Session -PoolName ewgtest_pool -Address 10.0.0.1%4 -PortNu ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-PoolMember], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-PoolMember


Add-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.0.0.1 -PortNumber 443 -Status Enabled -Partition dev
Invoke-RestMethodOverride : "404 Not Found: Object not found - 10.0.0.1:443
At C:\Users\d92495j\G\_Tasks\F5 PowerShell\POSH-LTM-Rest\F5-LTM\Public\Add-PoolMember.ps1:85 char:33
+ ...             Invoke-RestMethodOverride -Method POST -Uri "$MembersLink ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RestMethodOverride
 
True

# In this second Add-PoolMember example, the poolmember is actually created.
```

I plan to spend some more time trying to understand why my environment is using the ip%{partition} before proposing other changes.

**Comment by vercellone** [comment]
Your results aren't surprising, except for the last one where Add-PoolMember throws an error but reportedly adds the pool member anyway.  In this scenario, Enable/Disable-PoolMember shouldn't impact anything since Get-Poolmember should return $null.  If it doesn't, we need to determine why and fix that.  (check the list of all pool members in that pool before and after)  If the list really does change despite the 404, then the code needs to check $Error to avoid even attempting Enable/Disable-PoolMember.

To fix the 1st Add-PoolMember error, just change the [IPAddress] type attribute on the $Address param declaration to [string].

**Comment by elijahgagne** [comment]
Here's a more detailed outline of how things are working. I've changed the IP address and condensed the formatting so that it's shorter.
```
PS C:\> Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.100.10.1:443 -Address 10.100.10.1%4 -Partition dev
PS C:\> Add-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.100.10.1 -PortNumber 443 -Status Enabled -Partition dev

Invoke-RestMethodOverride : "404 Not Found: Object not found - 10.100.10.1:443
At C:\\G\_Tasks\F5 PowerShell\POSH-LTM-Rest\F5-LTM\Public\Add-PoolMember.ps1:85 char:33
+ ...             Invoke-RestMethodOverride -Method POST -Uri "$MembersLink ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RestMethodOverride
 
True
PS C:\> Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.100.10.1:443 -Address 10.100.10.1%4 -Partition dev

Name            Partition Address       Description Monitor Session         State   
----            --------- -------       ----------- ------- -------         -----   
10.100.10.1:443 dev       10.100.10.1%4             default monitor-enabled checking

PS C:\> Remove-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.100.10.1 -Partition dev -Confirm:$false
PS C:\> Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.100.10.1:443 -Address 10.100.10.1%4 -Partition dev

Name            Partition Address       Description Monitor Session         State   
----            --------- -------       ----------- ------- -------         -----   
10.100.10.1:443 dev       10.100.10.1%4             default monitor-enabled checking

PS C:\> Remove-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.100.10.1%4 -Partition dev -Confirm:$false
PS C:\> Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.100.10.1:443 -Address 10.100.10.1%4 -Partition dev

PS C:\> $Uri = "https://ltm-1.organization.com/mgmt/tm/ltm/node/~dev~10.100.10.1"
PS C:\> Invoke-RestMethodOverride -Method DELETE -Uri $Uri -Credential $Credential
PS C:\> Add-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.100.10.1 -PortNumber 443 -Status Enabled -Partition dev

Name            Partition Address       Description Monitor Session         State   
----            --------- -------       ----------- ------- -------         -----   
10.100.10.1:443 dev       10.100.10.1%4             default monitor-enabled checking
True

PS C:\> Remove-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Address 10.100.10.1%4 -Partition dev -Confirm:$false
PS C:\> Get-PoolMember -F5Session $F5Session -PoolName ewgtest_pool -Name 10.100.10.1:443 -Address 10.100.10.1%4 -Partition dev
PS C:\> 
```

**Comment by vercellone** [comment]
No bueno.  Something obviously wrong with that first POST.  I'd run through these 2 scenarios again one at a time with Fiddler enabled.  Save each scenario as a separate debugging session and compare the raw requests and responses, paying particular attention to the POSTs initiated by Add-PoolMember.  I suspect that will uncover an obvious discrepancy.  Or, at least provide evidence that can be posted for review and feedback over on the devcentral forums.

**Comment by elijahgagne** [comment]
I have found that there are two scenarios for adding a pool member to an existing pool, in regards to the node:
1) it does NOT already exist
2) it does already exist

With the current implementation, for *#*1, I do not get any errors. The JSON used to add the pool member looks like `@{name="10.200.30.4:443";partition="dev";address="10.200.30.4";description=""}`

For *#*2, I get an error adding the pool member (HTTP 404), but the pool member is added. The JSON used to add the pool member looks like `@{name="10.200.30.4:443"}`. If the JSON from *#*1 is used in this scenario, then it also works and I do not get an error. 

I created [a gist](https://gist.github.com/elijahgagne/db72df1dec90ea89ddfb3d70e58764d2) demoing this:

- Test 1 shows *#*1 working
- Test 2 shows *#*2 with the error
- Test 3 shows *#*2 working

From my perspective, I would be curious to know if Test 3 also works for you. If it does, then perhaps we can change Add-PoolMember to work like that. If it doesn't work for you, then I will look into an adaption to Add-PoolMember that will work for me, but not break you.

**Comment by vercellone** [comment]
Test 3 doesn't work for me.  It is the same scenario that prompted Issue #28.  The JSON fix was based on: [Add a new pool with an existing node](https://devcentral.f5.com/questions/add-a-new-pool-with-an-existing-node).

**Comment by elijahgagne** [comment]
I've submitted pull #56 to address the original issue. 

I've been trying to get something to work where `$JSONBody = @{name="$serverName"}` but I've had no luck yet. I've created [a more explicit test](https://gist.github.com/elijahgagne/00fdae727369be2116211fd1ce3df67f) where I make it clear that the node exists in both the Common and secondary partition. For this test I also changed to using name=$serverName and address=$serverIp because I think you mentioned that that's how your environment is generally setup. I don't see why this new test would produce any different results for you, but if you happen to see anything that makes your setup different than mine, please let me know. My version of the LTM is BIG-IP 11.6.0 Build 6.27.442 Engineering Hotfix HF6.

**Comment by joel74** [comment]
I've done what testing I can on this pull request, but it's necessarily limited since I just have the one partition. I can add and remove a pool member to an empty pool where the node/member already is present in another pool, and disabling/enabling a virtual server still work for me. I'm having to move away from using computer names in the pool member functions because the name-to-IP address translation fails for me (computers register with DNS on a back-end NIC and use a separate NIC to talk to the F5). 

All this to say, I'm good from my end with this pull request, but I'll wait for Jason to weigh in before merging. Thanks.

**Comment by vercellone** [comment]
#### Based on [elijahgagne:Issue54](https://github.com/https://github.com/elijahgagne/POSH-LTM-Rest/tree/Issue54)
**Test-Pool**: Good.
**Test-VirtualServer**: Good.
**(Dis|En)able-VirtualServer**: Good.  I see that Enabled is already included in the default column output.  Please remove the -AsBoolean and -ErrorMessage args from the Invoke-RestMethodOverride.
**Get-(HealthMonitor|iRule)**: These filter by Partition only when specifying -Partition and -Application without also specifying -Name.
**Get-PoolMember**: Good. Not your fault, but I think the GetHostAddresses code needs to be revisited.  OK with me to leave as-is for this PR.
**Get-(Pool|VirtualServer)**: Good. But, I recommend the following conditional logic for readability/maintenance instead of your current if..else..:
```PowerShell
$items = Invoke-NullCoalescing {$JSON.items} {$JSON}
if(![string]::IsNullOrWhiteSpace($Application)) {
    $items = $items | Where-Object {$_.fullPath -eq "/$($_.partition)/$Application.app/$($_.name)"}
}
$items | Add-ObjectDetail -TypeName 'PoshLTM.Pool'
```

**Comment by elijahgagne** [comment]
Very helpful, thanks! I've updated my pull request to address all your recommendations/comments minus revisiting Get-PoolMember. Two notes:
 - Get-HealthMonitor uses the filtering `$_.fullPath -like "/$Partition/$Application.app/*`. I found the health monitor object does not have partition property and the name is the same as the fullName (at least that's what I'm seeing in my environment). If you see something different in your environment or have an idea of a better filter that would be interesting.
 - For Get-iRule, I don't have any iApps (or iApp templates) that allow for creating the iRule directly in the iApp (we create the iRules in the Common partition and then have the iApp reference them). So I wasn't able to test my code change.

**Comment by vercellone** [comment]
Excellent.  This all checks out in my environment.

My health monitors' partition, name, and fullPath are intact and align with what we have seen elsewhere.  I verified Get-HealthMonitor works for me using either filtering method.
```PowerShell
$items = $items | Where-Object {$_.fullPath -like "/$Partition/$Application.app/*"}
$items = $items | Where-Object {$_.fullPath -eq "/$($_.partition)/$Application.app/$($_.name)"}
```
If you create a brand new health monitor, does it exhibit the same behavior?

**Comment by joel74** [comment]
Sounds like we're clear to merge this pull request. If I don't hear otherwise, I'll proceed with that at 12p CDT today. Thanks.

**Comment by elijahgagne** [comment]
I agree, I think we are good to merge. But I will say that I feel slightly unsettled that things are not as consistent as I would like them. If a better solutions emerges I would be happy to revisit this. 

I just tested creating a new iApp that had a new monitor and then checked it:

```
$Uri = "https://$ltm/mgmt/tm/ltm/monitor/$type/~$partition~$($application).app~$($monitor)?ver=11.6.0"
$Response = Invoke-RestMethodOverride -Method GET -Uri $Uri -Credential $Credential
$Response | fl name, partition
```
I got the same results that name = fullName and there was no partition property
```
name : /dev/ewgtest.app/ewgtest_http_monitor
```

I checked the iApp template and found that it runs this command to create the monitor:
```
set monitor_name [tmsh::run_proc f5.app_utils:create_monitor \
$tmsh::app_name $monitor_type $monitor_interval "$monitor_send" \
"$monitor_recv" "$http_version" $monitor_dns_name]
```

Looking at the [create_monitor](https://devcentral.f5.com/wiki/iApp.app-utils-CLI-script-include.ashx#create_monitor:_42) function, nothing stands out to me suggesting that we are doing something strange to create the monitor.

As a side note, once/if these changes are merged, shall we close this issue and #54? I am still interested in getting Add-PoolMember to work 100% of the time for all of us, but perhaps it would be appropriate to open a separate issue on that.

**Comment by joel74** [comment]
Ok, Thanks, Elijah. We can leave this issue open until it's decided what to do about the missing partition property. I agree that a new issue for hammering out any remaining issues with Add-PoolMember is probably the best approach.

**Comment by vercellone** [comment]
#108 reveals that the %4 suffix is an F5 [Route Domain](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-ip-routing-administration-11-2-0/2.html).  For the sake of consistency, the -Address parameter should be of the same type for all cmdLets that support it.  Currently, Get-PoolMember is [string[]] and Add-PoolMember is [IPAddress[]] and a separate RouteDomain parameter.  Instead, we should make it a custom type which derives from IPAddress but accommodates an optional route domain suffix without error.  I'll explore that possibility and submit a backward-compatible PR when proven.

**Comment by vercellone** [comment]
I've created #127 for the RouteDomain and Address inconsistency, which also covers revisiting the use of GetHostAddresses.  A PR will follow shortly.

I had to re-read through the history to conclude that only the partition-less health monitor behavior remains outstanding.  Is anyone opposed to creating a new issue for that and closing this one?

**Comment by elijahgagne** [comment]
Hi Jason, I just re-read everything and I agree that closing this issue and creating a new one for the partition-less health monitor makes sense to me.

**Comment by joel74** [comment]
Agreed - for clarity's sake, let's close this and create a new issue for that one item.

**Comment by vercellone** [comment]
#131 opened.  @joel74: Please close this issue.

**Comment by joel74** [comment]
Closing
