### ISSUE TITLE
Check format of JSON that Get-PoolMemberStats returns in v12.0 / 12.1

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#61]
In v 11.6, one can retrieve the pool member stats and then select the expanded property 'serverside.curConns' to get the connection count of the specified pool member. This doesn't work in v12.1. It claims this property cannot be found. A quick comparison of the results shows that that JSON returned is structured differently between v11.6 and 12.1.

**Comment by oribe** [comment]
Hi
Any news about this one?

**Comment by joel74** [comment]
I reached out to Joe Pruitt last week, who's one of the best qualified for saying how stats differ in iControlREST between versions, and he said "Between 11.6 and 12.0 there were a few breaking changes introduced and I’m not sure to what degree stats were involved.  I believe 12.0-12.1 was a lot more stable." He's continuing to look into it. I know that v12.1 uses a nested stats object that we'll need to expand to get this data. We haven't yet had to do anything in the module that depends on what version of iControlREST is being used, but it seems like we're at the point where we'll need to start differentiating. I'll keep working on this.

**Comment by oribe** [comment]
Thanks Joel.
Meanwhile, if anyone needs a quick workaround:
`(Get-PoolMember -Name 'membername' | Get-PoolMemberStats).PSObject.Properties.Value.nestedStats.entries`

**Comment by joel74** [comment]
Cheers, oribe!

**Comment by wrapsbear** [comment]
Great news, the POSH pasted by @oribesser above works on 13.0 as well!    Thanks @oribesser !

**Comment by joel74** [comment]
Fixed with PR #115
