### ISSUE TITLE
Set-iRule should use force parameter, not overwrite.

### ISSUE THREAD

**Issue by sanderma** [joel74/POSH-LTM-Rest#63]
To comply with standard, change overwrite parameter to force, and add alias to overwrite for backwards compatibility.

**Comment by joel74** [comment]
Hi, Sander, I believe this can be closed, correct?
Thanks, Joel

**Comment by sanderma** [comment]
Yes correct, its fixed.

Op di 11 okt. 2016 17:19 schreef joel <notifications@github.com>:
