### ISSUE TITLE
Consider renaming Get-Partition to Get-AdminPartition or Get-LTMPartition

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#69]
I've been recently informed by the folks at PowerShellGallery that, since our function Get-Partition has the same name as the PS4 Storage cmdlet Get-Partition, it's recommended that we change the name of our Get-Partition function to something else.

Fortunately, it looks like the only places we reference this are in ArgumentCompletion.ps1 and Get-Partition.ps1 itself.

Thoughts?

**Comment by vercellone** [comment]
I have no objections.  I like Get-AdminPartition within our context, but if we are trying to prevent future collisions/ambiguity Get-LTMPartition or Get-F5Partition might be better.  Use your best judgement.

**Comment by joel74** [comment]
Thanks, Jason. After some reflection, I'm thinking Get-BIGIPPartition is probably the most accurate. I'll make that change tomorrow.

**Comment by joel74** [comment]
Merged.
