### ISSUE TITLE
'LTM token request' authentication is not working

### ISSUE THREAD

**Issue by oribe** [joel74/POSH-LTM-Rest#74]
I'm testing on BIG-IP 11.6.0 Build 6.0.442 Hotfix HF6.
**New-F5Session** is choosing the **Invoke-RestMethodOverride** without the Credential or WebSession parameters, which in turn chooses the **Invoke-RestMethod** without the Credential or WebSession parameters, and then fails with:
_Invoke-RestMethodOverride : "401 F5 Authorization Required:_ 

The same request passed with a WebSession object with a credential is working.

**Comment by vercellone** [comment]
Sorry to hear that.  Unfortunately, most of the REST API resources that I've found on devcentral.f5.com assume version 12+.  So, we're left to trial and error for 11.5 and 11.6.

Given your experience, my recommendation is to revert the following commits:
824326c
f58a711

**Comment by joel74** [comment]
It's been working fine for me on 11.6 HF4. I'll do some more testing on Monday, to see if I can figure out what's causing this scenario.

**Comment by joel74** [comment]
Hi, oribe, are you passing a value for the LTMCredentials param to New-F5Session when it fails? Thanks.

**Comment by oribe** [comment]
Hi Joel, sorry for the delay.
I am passing LTMCredentials, then the following is happening:

- In 'New-F5Session.ps1' it detects ver 11.6 and then it is running:
`$AuthURL = "https://$LTMName/mgmt/shared/authn/login";
$JSONBody = @{username = $LTMCredentials.username; password=$LTMCredentials.GetNetworkCredential().password} | ConvertTo-Json
$Result = Invoke-RestMethodOverride -Method POST -Uri $AuthURL -Body $JSONBody -ContentType 'application/json'`

- In 'Invoke-RestMethodOverride.ps1' the switch statement is choosing 'Default' because no Credential or WebSession parameters were passed. 'Default' is running:
`Invoke-RestMethod -Method $Method -Uri $URI -Body $Body -Headers $Headers -ContentType $ContentType`
which throws:
`Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Invoke-RestMethod -Method $Method -Uri $URI -Body $Body -Headers $Hea ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`



I am temporarily working around this by adding this to the 11.6 'else' statement in 'New-F5Session.ps1':
`$session.Credentials = $LTMCredentials
 $Result = Invoke-RestMethodOverride -Method POST -Uri $AuthURL -Body $JSONBody -ContentType 'application/json' -WebSession $session`

**Comment by joel74** [comment]
Hi, oribe, thanks for the additional info. It seems like what's happening is that your request to get an auth token is failing because the LTM is requesting authorization. My understanding is that it shouldn't be (per [this page](https://devcentral.f5.com/wiki/icontrol.authentication_with_the_f5_rest_api.ashx)), but maybe this is somehow related to the code not using a LoginReference. Is your LTM doing local or remote?

Your work-around is actually something Jason initially had in his commit, and then I suggested he take it out because I believed it wasn't needed. I see no harm in adding in back in, but I'll let Jason weigh in as well.

**Comment by vercellone** [comment]
I have no objection.  I updated my branches and created PR #75 to fix/revert it.

**Comment by oribe** [comment]
I am using a local user to authenticate, passing my AD credentials doesn't work at all, even when passing the Credential object.
