### ISSUE TITLE
Can we stop using 'ConvertTo-SecureString' in 'Invoke-RestMethodOverride.ps1'?

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#77]
The module got dinged by PowerShellGallery on the latest submission for including a call to ConvertTo-SecureString in Invoke-RestMethodOverride.ps1. I looked through the code in New-F5Session.ps1 and Invoke-RestMethodOverride.ps1, and I'm not clear on why we're calling ConvertTo-SecureString in the first place. The code in question (ln. 39) is only used for LTM ver < 11.6. When we create the WebSession object for accessing LTM v < 11.6, we use the Credentials object that is passed to New-F5Session, and the password in that Credentials object are already a secure string.

I believe we could do away with ln. 39 and just pass $WebSession.Credentials as the Credential parameter in ln 40. However, I don't have access to a version of LTM that is less than 11.6 to test this theory, so I need to punt to someone else. Thanks.

**Comment by vercellone** [comment]
I wish it were that simple.  $WebSession.Credentials -is [System.Net.NetworkCredential].  As far as I know, it can't be converted to [System.Management.Automation.PSCredential] any other way.  LTMCredentials will have to be passed to Invoke-RestMethodOverride another way.

The best alternative I can imagine is to create a private variation of Invoke-RestMethodOverride with an -F5Session param.  All the Credential/WebSession/Other conditional logic could be encapsulated there based on F5Session, and the public Invoke-RestMethodOverride could either be reverted to it's more generic implementation or removed entirely.

**Comment by joel74** [comment]
Thanks, Jason. Sounds like this is going to require a bit of thinking, so we can keep the solution as clean as possible.

**Comment by joel74** [comment]
I think I found a fix. System.Net.NetworkCredential stores both the password as plain text and as a secure string.

So in Invoke-RestMethodOverride.ps1, ln 39, instead of having:

`(ConvertTo-SecureString $WebSession.Credentials.Password -AsPlainText -Force)`

we could just call
`$WebSession.Credentials.SecurePassword`

I'm not able to test this, though, since I don't have an LTM that's less that 11.6. Seems sound in theory to me, though.

**Comment by vercellone** [comment]
That works for me.

**Comment by joel74** [comment]
Fixed with this commit: https://github.com/joel74/POSH-LTM-Rest/commit/67931df3a44d44a5de9a6fabb0bcb550c2404601
