### ISSUE TITLE
Can't get New-Pool with MemberDefinitionList parameter to work with existing nodes

### ISSUE THREAD

**Issue by maxpowerbjh** [joel74/POSH-LTM-Rest#78]
When running the below command to create a new Pool with a node that already exists.

New-Pool -F5Session $F5Session -Name "TEST_POOL" -Partition "TEST" -MemberDefinitionList @("SERVERTEST,80")

Add-PoolMember : Cannot process argument transformation on parameter 'Address'. Cannot convert value "SERVERTEST" to type "System.Net.IPAddress". 
Error: "An invalid IP address was specified."
At C:\Program Files\WindowsPowerShell\Modules\F5-LTM\Public\New-Pool.ps1:49 char:90
+ ... ition -Address $Address -PortNumber 80 -Status "Enabled" -Name "SERVERTEST"
+                    ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-PoolMember], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-PoolMember

**Comment by joel74** [comment]
The MemberDefinitionList param expects an IP address, though the example shows it expecting a server name. The New-Pool function needs to be updated to accept either an IP address or a server name, but for now, it should work if you pass in an IP address.

**Comment by vercellone** [comment]
Separate Add-PoolMember -ComputerName calls should be viable as well.  But, I suppose computer name ip resolution could be added to New-Pool for convenience.

**Comment by maxpowerbjh** [comment]
Thanks!  I did end up using the Add-PoolMember in place of New-Pool.
Just for your reference, when I tried using an IP address instead I got the below message.  Again this is with a Node that already exists.

Invoke-RestMethodOverride : "400 Bad Request: 0107003a:3: Pool member node (/COR/10.217.47.85) and existing node (/COR/SERVERTEST) cannot use the 
same IP Address (10.217.47.85%1).
At C:\Program Files\WindowsPowerShell\Modules\F5-LTM\Public\Add-PoolMember.ps1:85 char:33
+                                 Invoke-RestMethodOverride -Method POST -Uri "$Me ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RestMethodOverride

Last thing.  I did have a need to update the Load Balancing Mode on a pool so I repurposed one of the other functions to be able to do that.  It's attached if you'd like to have it.

My company is switching from an A10 load balancer to an F5 so I'm trying to write some conversion scripts to set everything up in an automated fashion, so I'm getting quite familiar with what you've written.
[Set-PoolLoadBalancingMode.ps1.txt](https://github.com/joel74/POSH-LTM-Rest/files/646820/Set-PoolLoadBalancingMode.ps1.txt)

**Comment by joel74** [comment]
Thanks for sending over the set load balancing mode function. I'll incorporate that functionality in the module. 

In regards to the error you're getting, I was able to repro the same message through the UI by first adding a pool member with one name, and then trying to add another pool member using a different name and the same IP address.

![image](https://cloud.githubusercontent.com/assets/10774597/21143681/46a31900-c10d-11e6-95f9-c03be358d80b.png)

Node entries are created automatically when a pool member is added, but F5 doesn't automatically clean them up when the pool member is deleted. You can call Get-Node to return all existing nodes, their names and IP addresses in the F5.

I'm open to suggestions if there's a better way to handle this, but I believe the PS module is just following the UI at this point.

Thanks,
Joel

**Comment by joel74** [comment]
Pull request added with Set-PoolLoadBalancingMode function added.

https://github.com/joel74/POSH-LTM-Rest/pull/79

**Comment by maxpowerbjh** [comment]
If I were doing it via the UI I'd switch the radio button to the "Node list" option and select the existing node.

Another addition: I took the Add-iRuleToVirtualServer function and modified it to set the default pool on a virtual server.  You can use it if you'd like.

What actually would be super cool is being able to use the Get-VirtualServer function to get a virtual server, then modify it locally within powershell to change whatever, then upload the whole object back into the F5.

[Set-VirtualServerPool.ps1.txt](https://github.com/joel74/POSH-LTM-Rest/files/655980/Set-VirtualServerPool.ps1.txt)

**Comment by joel74** [comment]
Hi, maxpowerbjh, I believe vercellone has created exactly what you were looking for with the Set-VirtualServer function he committed. It accepts a VirtualServer object in its pipeline and sends it to the LTM. Check it out when you have a moment.

**Comment by maxpowerbjh** [comment]
Looks good to me, it does what i need it to do.  In some of the other Set-*
commands there is a True\False result that gets returned, would you kindly
add it this new Set-VirtualServer as well?

Brian

**Comment by vercellone** [comment]
The others shouldn't return True/False.  Please use -PassThru to have the newly created or modified object returned.
