### ISSUE TITLE
Splitting methods into files

### ISSUE THREAD

**Issue by jangins101** [joel74/POSH-LTM-Rest#8]
Do you think it would be useful to split each of the methods into individual files containing the functions? That way, new files could be added to the project and the `.psm1` file could just dot source all the `.ps1` files (maybe in a subfolder too).

**Comment by joel74** [comment]
It's an interesting idea, but it would kind of defeat the point of having a module, if we're then having to keep up with 20+ individual function files. Is the concern that the module file is too monolithic and difficult to work with?
Thanks.

**Comment by jangins101** [comment]
Yea. I've been working on a module for some stuff I'm doing at work, and found that having the `psm1` file import all `ps1` files in the module directory made it easy to insert new methods into the module, and finding a method quickly is doable. That way, you still get the benefit of having a portable module while maintaining each method individually. 

I figure another thing would be if someone wanted to add a method, they could just add a new file and submit a merge request back into the master.

**Comment by joel74** [comment]
Hi. Sorry for the delay getting back to you. It might be something I want to do in the future, so I'll leave this issue open for now. Thanks.

**Comment by vercellone** [comment]
+1 vote for splitting

**Comment by vercellone** [comment]
Commit c3aedc650296172b8ed3d019b8da6bd604b4240c provides a preview of splitting functions into individual .ps1 files.

**Comment by joel74** [comment]
Thanks. Let me chew on this for a little bit and review what you've committed.

**Comment by joel74** [comment]
I like this and I want to move forward with it. I'm wondering, though, about the \Public and \Private groupings. Is the thinking that scripts/functions in the Public group would be made exportable and ones in the Private group would be hidden?

**Comment by vercellone** [comment]
Yes, exactly.  Private functions are internal, not exported.  I observed this in @proxb's [PoshRSJob repo](https://github.com/proxb/PoshRSJob) and intend to adopt it for other projects.
