### ISSUE TITLE
Set-iRule only create rules in the Common partition

### ISSUE THREAD

**Issue by maxpowerbjh** [joel74/POSH-LTM-Rest#80]
Tried creating a new rule with the -Partition parameter.  It created the rule, but always saved it to the Common partition instead of the partition I specified.

**Comment by joel74** [comment]
Thanks for catching that. I'll take a look

**Comment by joel74** [comment]
Fixed with this commit: https://github.com/joel74/POSH-LTM-Rest/commit/4eb9451ddb1b61af6d9c4e6a5714659d8a5ffe09
I'll merge this in once Jason's had a chance to look at the pull request for Set-PoolLoadBalanceMode

**Comment by joel74** [comment]
Merged.
