### ISSUE TITLE
F5Session global variable

### ISSUE THREAD

**Issue by dmills488** [joel74/POSH-LTM-Rest#9]
Please excuse my ignorance... But how is the F5Session function supposed to be used?

I had to modify the code to create a F5Session global variable:
$global:F5Session = [pscustomobject]@{BaseURL = $BaseURL; Credential = $Credential}

I then run Get-F5Session followed by whatever function I want to perform on the LTM.

**Comment by joel74** [comment]
Hi,

The way I've been using it is to generate an F5 session object that I store in a variable, and then pass that variable to any function that needs the session object. I.e.:

$F5Session = Get-F5session -LTMName '10.1.1.1' -F5UserName 'admin' -F5Password 'password'

Once you have the local variable, you don't need to call Get-F5Session again. 

In my scenario, I have multiple F5s that I might connect to, so I may need to reference multiple session objects. 

Does that answer your question?
Cheers,
Joel

**Comment by joel74** [comment]
Closing. Please reopen or open new if you still have questions.
Thanks.
