### ISSUE TITLE
Feature Request: Create Remove-iRule function

### ISSUE THREAD

**Issue by Jeff-Gibbs** [joel74/POSH-LTM-Rest#99]
I'm able to create an iRule but not able to remove/delete one. If their is away to delete it please point me to the correct function.
Thanks Again

**Comment by joel74** [comment]
Correct, there is currently no way to remove an iRule. I'll start working on a new function for it, but I'd like to note that this might be a pretty powerful function. It will have a ConfirmImpact of High, for sure, but it will also need to automatically remove the iRule from all assigned virtual servers before deleting it from the LTM, and to do this, it will need to look at every single virtual server on the LTM.

**Comment by elijahgagne** [comment]
Just a thought, I believe the LTMs are already going to do the check to make sure that the iRule is not currently used by any virtual servers. When I make a HTTP call to remove an iRule that is in use, I get a helpful HTTP error message. Perhaps it would be sufficient to make the request to remove the iRule and then let the LTM response fall through. 

My thought is, if the iRule is in use, make it incumbent on the requester to address that removing it from all virtual servers before dropping the iRule. That's consistent with what the web interface does and it ensures the requester is fully aware of the impact.

**Comment by joel74** [comment]
That makes sense to me, Elijah. I like that solution.

**Comment by joel74** [comment]
Please see PR#100 with my proposed Remove-iRule function, as well as some other fixes / tweaks.

**Comment by Jeff-Gibbs** [comment]
Thanks Joel, I'll test remove-iRule tonight

**Comment by Jeff-Gibbs** [comment]
I tested get -irule and remove-irule they both worked :)

**Comment by joel74** [comment]
Thanks, Jeff-Gibbs. I've merged the changes into the master branch.
